export const exercisesSeedData = [
  {
    name: 'Walking',
    category: 'cardio',
    difficulty: 'beginner',
    targetMuscles: ['legs', 'glutes', 'core'],
    benefits: [
      'Low impact and accessible',
      'Improves cardiovascular health',
      'Helps with weight management',
      'Reduces stress and anxiety',
      'Strengthens bones and joints',
    ],
    instructions: [
      'Wear comfortable shoes and loose clothing',
      'Start with 5 minutes of slow pace to warm up',
      'Maintain a brisk pace where you can still talk',
      'Swing your arms naturally',
      'Cool down with 5 minutes of slower pace',
      'Stretch after walking',
    ],
    duration: '30 minutes',
    caloriesBurn: '150-200',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,walking',
    tags: ['cardio', 'beginner', 'low-impact', 'weight-loss'],
  },
  {
    name: 'Running',
    category: 'cardio',
    difficulty: 'intermediate',
    targetMuscles: ['legs', 'glutes', 'core', 'hips'],
    benefits: [
      'Excellent for cardiovascular fitness',
      'Burns significant calories',
      'Improves mental health',
      'Strengthens bones',
      'Builds endurance',
    ],
    instructions: [
      'Warm up with dynamic stretches for 5 minutes',
      'Start at a comfortable pace',
      'Maintain upright posture with slight forward lean',
      'Land mid-foot, not on heels',
      'Breathe rhythmically',
      'Cool down with 5 minutes of walking',
      'Stretch hamstrings and quads after',
    ],
    duration: '20-30 minutes',
    caloriesBurn: '300-400',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,running',
    tags: ['cardio', 'intermediate', 'high-calorie-burn', 'endurance'],
  },
  {
    name: 'Planks',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['core', 'shoulders', 'back', 'glutes'],
    benefits: [
      'Strengthens entire core',
      'Improves posture and stability',
      'Reduces back pain risk',
      'No equipment needed',
      'Engages multiple muscle groups',
    ],
    instructions: [
      'Start in push-up position, lower forearms to ground',
      'Keep body in straight line from head to heels',
      'Engage core and glutes',
      'Hold position without sagging hips',
      'Breathe steadily throughout',
      'Hold for 20-60 seconds',
    ],
    duration: '30-60 seconds',
    caloriesBurn: '2-5 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,planks',
    tags: ['core', 'strength', 'bodyweight', 'beginner'],
  },
  {
    name: 'Push-Ups',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['chest', 'shoulders', 'triceps', 'core'],
    benefits: [
      'Builds upper body strength',
      'Engages core for stability',
      'No equipment required',
      'Can be modified for different levels',
      'Improves functional fitness',
    ],
    instructions: [
      'Start in plank position with hands slightly wider than shoulders',
      'Lower body until chest nearly touches ground',
      'Keep elbows at 45 degrees to body',
      'Push back up to starting position',
      'Keep core engaged throughout',
      'Do knee push-ups if standard is too hard',
    ],
    duration: '3 sets of 10-15 reps',
    caloriesBurn: '7 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,push-ups',
    tags: ['strength', 'upper-body', 'bodyweight', 'chest'],
  },
  {
    name: 'Squats',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['quads', 'glutes', 'hamstrings', 'core'],
    benefits: [
      'Strengthens lower body',
      'Builds functional movement',
      'Burns calories effectively',
      'Improves mobility and balance',
      'Engages core stabilizers',
    ],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Keep chest up and back straight',
      'Lower hips back and down like sitting in chair',
      'Go as low as comfortable, thighs parallel to ground',
      'Push through heels to stand back up',
      'Keep knees tracking over toes',
    ],
    duration: '3 sets of 12-15 reps',
    caloriesBurn: '8 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,squats',
    tags: ['strength', 'lower-body', 'bodyweight', 'glutes'],
  },
  {
    name: 'Jumping Jacks',
    category: 'cardio',
    difficulty: 'beginner',
    targetMuscles: ['full body', 'legs', 'shoulders', 'core'],
    benefits: [
      'Full body cardio exercise',
      'Improves cardiovascular endurance',
      'Burns calories quickly',
      'Increases bone density',
      'Improves coordination',
    ],
    instructions: [
      'Stand with feet together, arms at sides',
      'Jump while spreading legs and raising arms overhead',
      'Land softly on feet',
      'Jump back to starting position',
      'Maintain steady rhythm',
      'Start with 30 seconds and increase gradually',
    ],
    duration: '1-3 minutes',
    caloriesBurn: '10 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,jumping-jacks',
    tags: ['cardio', 'full-body', 'beginner', 'warm-up'],
  },
  {
    name: 'Mountain Climbers',
    category: 'cardio',
    difficulty: 'intermediate',
    targetMuscles: ['core', 'shoulders', 'hips', 'legs'],
    benefits: [
      'Full body cardio and strength',
      'Excellent for core stability',
      'Increases heart rate quickly',
      'Burns significant calories',
      'Improves coordination and agility',
    ],
    instructions: [
      'Start in plank position with arms extended',
      'Drive one knee toward chest',
      'Quickly switch legs, alternating',
      'Keep hips down and core engaged',
      'Maintain steady pace',
      'Breathe rhythmically with movement',
    ],
    duration: '30-60 seconds',
    caloriesBurn: '12 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,mountain-climbers',
    tags: ['cardio', 'core', 'full-body', 'hiit'],
  },
  {
    name: 'Lunges',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['quads', 'glutes', 'hamstrings', 'calves'],
    benefits: [
      'Builds leg strength and balance',
      'Improves hip flexibility',
      'Engages core for stability',
      'Functional movement pattern',
      'Can be done anywhere',
    ],
    instructions: [
      'Stand tall with feet hip-width apart',
      'Step forward with one leg',
      'Lower hips until both knees are at 90 degrees',
      'Front knee above ankle, back knee above ground',
      'Push through front heel to return to start',
      'Alternate legs',
    ],
    duration: '3 sets of 10 reps per leg',
    caloriesBurn: '7 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,lunges',
    tags: ['strength', 'lower-body', 'balance', 'legs'],
  },
  {
    name: 'Bicycle Crunches',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['abs', 'obliques', 'hip flexors'],
    benefits: [
      'Targets all abdominal muscles',
      'Engages obliques for waist definition',
      'Improves core endurance',
      'No equipment needed',
      'Low impact',
    ],
    instructions: [
      'Lie on back with hands behind head',
      'Lift shoulders off ground',
      'Bring one knee toward chest while twisting opposite elbow toward it',
      'Alternate sides in pedaling motion',
      'Keep lower back pressed to ground',
      'Breathe out with each twist',
    ],
    duration: '3 sets of 15-20 reps',
    caloriesBurn: '6 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,bicycle-crunches',
    tags: ['abs', 'core', 'bodyweight', 'obliques'],
  },
  {
    name: 'Burpees',
    category: 'hiit',
    difficulty: 'advanced',
    targetMuscles: ['full body', 'chest', 'legs', 'core', 'arms'],
    benefits: [
      'Ultimate full body exercise',
      'Burns maximum calories',
      'Builds strength and endurance',
      'Improves cardiovascular fitness',
      'No equipment needed',
    ],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Squat down and place hands on ground',
      'Jump feet back into plank position',
      'Perform a push-up',
      'Jump feet back to squat position',
      'Jump up explosively with arms overhead',
    ],
    duration: '3 sets of 8-12 reps',
    caloriesBurn: '15 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,burpees',
    tags: ['hiit', 'full-body', 'advanced', 'calorie-burn'],
  },
  {
    name: 'Stretching',
    category: 'flexibility',
    difficulty: 'beginner',
    targetMuscles: ['full body', 'flexibility'],
    benefits: [
      'Improves flexibility and range of motion',
      'Reduces muscle tension',
      'Prevents injury',
      'Improves posture',
      'Promotes relaxation',
    ],
    instructions: [
      'Start with neck rolls and shoulder shrugs',
      'Stretch arms overhead and to sides',
      'Do standing forward fold for hamstrings',
      'Perform quad stretches holding each leg',
      'Sit and stretch for inner thighs',
      'Hold each stretch for 20-30 seconds',
      'Do not bounce, breathe deeply',
    ],
    duration: '10-15 minutes',
    caloriesBurn: '2 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,stretching',
    tags: ['flexibility', 'recovery', 'beginner', 'cool-down'],
  },
  {
    name: 'Jump Rope',
    category: 'cardio',
    difficulty: 'intermediate',
    targetMuscles: ['legs', 'arms', 'shoulders', 'core'],
    benefits: [
      'Excellent cardiovascular workout',
      'Burns calories very efficiently',
      'Improves coordination and agility',
      'Strengthens bones',
      'Portable and inexpensive',
    ],
    instructions: [
      'Hold rope handles at hip level',
      'Swing rope overhead with wrist motion',
      'Jump slightly as rope passes under feet',
      'Land softly on balls of feet',
      'Keep elbows close to body',
      'Start with 30 seconds, rest, repeat',
    ],
    duration: '10-15 minutes',
    caloriesBurn: '12-15 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,jump-rope',
    tags: ['cardio', 'coordination', 'calorie-burn', 'hiit'],
  },
  {
    name: 'Deadlifts',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['hamstrings', 'glutes', 'back', 'core', 'forearms'],
    benefits: [
      'Builds total body strength',
      'Strengthens posterior chain',
      'Improves posture',
      'Functional movement pattern',
      'Burns significant calories',
    ],
    instructions: [
      'Stand with feet hip-width apart, barbell over mid-foot',
      'Hinge at hips, bend knees slightly',
      'Grip bar just outside knees',
      'Keep back flat and chest up',
      'Drive through heels to stand up',
      'Lower bar by hinging at hips',
    ],
    duration: '3 sets of 8-10 reps',
    caloriesBurn: '10 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,deadlifts',
    tags: ['strength', 'full-body', 'posterior-chain', 'compound'],
  },
  {
    name: 'Bench Press',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['chest', 'shoulders', 'triceps', 'core'],
    benefits: [
      'Builds upper body pushing strength',
      'Targets chest effectively',
      'Increases bone density',
      'Improves arm strength',
      'Compound movement for mass',
    ],
    instructions: [
      'Lie on bench with feet planted',
      'Grip bar slightly wider than shoulder width',
      'Unrack bar and lower to mid-chest',
      'Touch chest and press bar up',
      'Keep elbows at 75 degrees',
      'Lock out at top without overextending',
    ],
    duration: '3 sets of 8-12 reps',
    caloriesBurn: '8 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,bench-press',
    tags: ['strength', 'chest', 'upper-body', 'compound'],
  },
  {
    name: 'Overhead Press',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['shoulders', 'triceps', 'core', 'upper chest'],
    benefits: [
      'Builds shoulder strength and size',
      'Improves overhead stability',
      'Engages core for balance',
      'Functional pushing movement',
      'Develops upper body power',
    ],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Hold bar at shoulder height, palms forward',
      'Press bar overhead until arms are extended',
      'Keep core tight and avoid arching back',
      'Lower bar back to shoulders',
      'Control the descent',
    ],
    duration: '3 sets of 8-10 reps',
    caloriesBurn: '7 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,overhead-press',
    tags: ['strength', 'shoulders', 'upper-body', 'compound'],
  },
  {
    name: 'Bent Over Rows',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['back', 'biceps', 'rear deltoids', 'core'],
    benefits: [
      'Builds back thickness and width',
      'Improves posture',
      'Strengthens grip',
      'Balances pushing muscles',
      'Compound movement for mass',
    ],
    instructions: [
      'Stand with feet hip-width apart, holding barbell',
      'Hinge forward at hips until torso is 45 degrees',
      'Keep back straight and core braced',
      'Pull bar to lower ribcage',
      'Squeeze shoulder blades at top',
      'Lower bar with control',
    ],
    duration: '3 sets of 8-12 reps',
    caloriesBurn: '7 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,bent-over-rows',
    tags: ['strength', 'back', 'upper-body', 'compound'],
  },
  {
    name: 'Pull-Ups',
    category: 'strength',
    difficulty: 'advanced',
    targetMuscles: ['back', 'biceps', 'shoulders', 'core'],
    benefits: [
      'Builds upper body pulling strength',
      'Targets back and biceps',
      'Improves grip strength',
      'No equipment needed (bar required)',
      'Measures relative strength',
    ],
    instructions: [
      'Grip pull-up bar with palms facing away',
      'Hang with arms fully extended',
      'Pull yourself up until chin is over bar',
      'Lower yourself with control',
      'Avoid swinging or kipping',
      'Use assisted band or negatives if needed',
    ],
    duration: '3 sets of 6-12 reps',
    caloriesBurn: '10 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,pull-ups',
    tags: ['strength', 'back', 'upper-body', 'advanced'],
  },
  {
    name: 'Dumbbell Curls',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['biceps', 'forearms'],
    benefits: [
      'Isolates and builds biceps',
      'Improves arm definition',
      'Can be done seated or standing',
      'Helps with grip strength',
      'Simple and effective',
    ],
    instructions: [
      'Stand holding dumbbells at sides, palms forward',
      'Keep elbows pinned to ribs',
      'Curl weights toward shoulders',
      'Squeeze biceps at top',
      'Lower with control for 3 seconds',
      'Do not swing body for momentum',
    ],
    duration: '3 sets of 10-15 reps',
    caloriesBurn: '5 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,dumbbell-curls',
    tags: ['strength', 'arms', 'biceps', 'isolation'],
  },
  {
    name: 'Tricep Dips',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['triceps', 'chest', 'shoulders'],
    benefits: [
      'Builds triceps strength and size',
      'Targets arms effectively',
      'Can use bench or parallel bars',
      'Improves pushing power',
      'Bodyweight or weighted',
    ],
    instructions: [
      'Place hands on bench edge behind you',
      'Extend legs forward, heels on ground',
      'Lower body by bending elbows to 90 degrees',
      'Push through palms to return up',
      'Keep back close to bench',
      'Add weight on lap for progression',
    ],
    duration: '3 sets of 10-15 reps',
    caloriesBurn: '6 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,tricep-dips',
    tags: ['strength', 'arms', 'triceps', 'bodyweight'],
  },
  {
    name: 'Calf Raises',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['calves', 'ankles'],
    benefits: [
      'Builds calf size and definition',
      'Improves ankle stability',
      'Supports running and jumping',
      'Can be done anywhere',
      'Simple movement pattern',
    ],
    instructions: [
      'Stand on edge of step or flat ground',
      'Raise heels as high as possible',
      'Hold at top for 1 second',
      'Lower heels below step level for stretch',
      'Control the movement throughout',
      'Add weight for progression',
    ],
    duration: '3 sets of 15-20 reps',
    caloriesBurn: '4 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,calf-raises',
    tags: ['strength', 'lower-body', 'calves', 'beginner'],
  },
  {
    name: 'Glute Bridges',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['glutes', 'hamstrings', 'core', 'lower back'],
    benefits: [
      'Activates and strengthens glutes',
      'Improves hip mobility',
      'Reduces lower back pain',
      'Great for posture',
      'No equipment needed',
    ],
    instructions: [
      'Lie on back with knees bent, feet flat',
      'Place arms at sides, palms down',
      'Push through heels to lift hips up',
      'Squeeze glutes at the top',
      'Hold for 2 seconds at top',
      'Lower hips back down with control',
    ],
    duration: '3 sets of 12-15 reps',
    caloriesBurn: '4 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,glute-bridges',
    tags: ['strength', 'glutes', 'lower-body', 'beginner'],
  },
  {
    name: 'Box Jumps',
    category: 'plyometric',
    difficulty: 'advanced',
    targetMuscles: ['quads', 'glutes', 'hamstrings', 'calves'],
    benefits: [
      'Builds explosive power',
      'Improves vertical jump',
      'Burns calories rapidly',
      'Enhances athletic performance',
      'Strengthens lower body',
    ],
    instructions: [
      'Stand facing a sturdy box or platform',
      'Slightly bend knees and swing arms back',
      'Jump explosively onto the box',
      'Land softly with both feet',
      'Stand up fully on the box',
      'Step down carefully, do not jump down',
    ],
    duration: '3 sets of 8-10 reps',
    caloriesBurn: '12 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,box-jumps',
    tags: ['plyometric', 'explosive', 'advanced', 'power'],
  },
  {
    name: 'Kettlebell Swings',
    category: 'hiit',
    difficulty: 'intermediate',
    targetMuscles: ['glutes', 'hamstrings', 'core', 'shoulders', 'back'],
    benefits: [
      'Full body explosive movement',
      'Builds posterior chain strength',
      'Excellent for fat burning',
      'Improves cardiovascular fitness',
      'Develops hip power',
    ],
    instructions: [
      'Stand with feet wider than shoulders',
      'Hold kettlebell with both hands',
      'Hinge at hips and swing bell back',
      'Drive hips forward to swing bell to chest height',
      'Keep core tight and back straight',
      'Let bell swing back and repeat',
    ],
    duration: '3 sets of 15-20 reps',
    caloriesBurn: '14 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,kettlebell-swings',
    tags: ['hiit', 'full-body', 'explosive', 'cardio'],
  },
  {
    name: 'Russian Twists',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['abs', 'obliques', 'core', 'hip flexors'],
    benefits: [
      'Targets oblique muscles',
      'Improves rotational strength',
      'Enhances core stability',
      'Can be done with or without weight',
      'Low impact',
    ],
    instructions: [
      'Sit with knees bent, feet slightly off ground',
      'Lean back slightly, keep back straight',
      'Clasp hands together at chest',
      'Rotate torso to the right',
      'Rotate to the left in controlled motion',
      'Add a weight for increased difficulty',
    ],
    duration: '3 sets of 20 reps (10 each side)',
    caloriesBurn: '5 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,russian-twists',
    tags: ['abs', 'core', 'obliques', 'bodyweight'],
  },
  {
    name: 'Leg Raises',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['lower abs', 'hip flexors', 'core'],
    benefits: [
      'Targets lower abdominal muscles',
      'Improves core strength',
      'Reduces lower back pain',
      'No equipment needed',
      'Can be done on floor or hanging',
    ],
    instructions: [
      'Lie flat on back with legs straight',
      'Place hands under glutes for support',
      'Keep legs straight and raise to 90 degrees',
      'Lower legs slowly without touching ground',
      'Keep lower back pressed to floor',
      'Control the movement throughout',
    ],
    duration: '3 sets of 10-15 reps',
    caloriesBurn: '5 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,leg-raises',
    tags: ['abs', 'core', 'lower-abs', 'bodyweight'],
  },
  {
    name: 'Dumbbell Shoulder Fly',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['shoulders', 'rear deltoids', 'upper back'],
    benefits: [
      'Isolates shoulder muscles',
      'Improves shoulder definition',
      'Strengthens rotator cuff',
      'Improves posture',
      'Prevents shoulder injuries',
    ],
    instructions: [
      'Hold dumbbells at sides, slight bend in elbows',
      'Raise arms to sides to shoulder height',
      'Keep palms facing down',
      'Squeeze shoulder blades at top',
      'Lower with control',
      'Do not use momentum',
    ],
    duration: '3 sets of 10-12 reps',
    caloriesBurn: '5 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,dumbbell-shoulder-fly',
    tags: ['strength', 'shoulders', 'isolation', 'upper-body'],
  },
  {
    name: 'Hip Thrusts',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['glutes', 'hamstrings', 'core'],
    benefits: [
      'Best glute activation exercise',
      'Builds strong and shapely glutes',
      'Improves hip thrust power',
      'Reduces lower back strain',
      'Can be weighted for progression',
    ],
    instructions: [
      'Sit on ground with back against bench',
      'Place barbell or weight over hips',
      'Plant feet firmly on ground',
      'Drive through heels to lift hips',
      'Squeeze glutes hard at top',
      'Lower hips with control',
    ],
    duration: '3 sets of 10-12 reps',
    caloriesBurn: '6 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,hip-thrusts',
    tags: ['strength', 'glutes', 'lower-body', 'hip-drive'],
  },
  {
    name: 'Step-Ups',
    category: 'cardio',
    difficulty: 'beginner',
    targetMuscles: ['quads', 'glutes', 'hamstrings', 'calves'],
    benefits: [
      'Builds leg strength and balance',
      'Functional everyday movement',
      'Low impact on joints',
      'Can be done anywhere with a step',
      'Improves coordination',
    ],
    instructions: [
      'Stand facing a sturdy step or bench',
      'Step up with right foot',
      'Drive through heel to stand on step',
      'Step down with right foot',
      'Alternate leading leg each rep',
      'Add weight for progression',
    ],
    duration: '3 sets of 12 reps each leg',
    caloriesBurn: '6 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,step-ups',
    tags: ['cardio', 'lower-body', 'beginner', 'balance'],
  },
  {
    name: 'Wall Sit',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['quads', 'glutes', 'hamstrings', 'core'],
    benefits: [
      'Builds leg endurance',
      'Strengthens quads and glutes',
      'Isometric exercise for stability',
      'No equipment needed',
      'Can be done anywhere',
    ],
    instructions: [
      'Stand with back against a wall',
      'Slide down until thighs are parallel to ground',
      'Keep knees at 90 degrees',
      'Hold position without moving',
      'Keep core engaged',
      'Breathe steadily throughout',
    ],
    duration: '30-60 seconds',
    caloriesBurn: '3 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,wall-sit',
    tags: ['strength', 'lower-body', 'isometric', 'endurance'],
  },
  {
    name: 'High Knees',
    category: 'cardio',
    difficulty: 'intermediate',
    targetMuscles: ['hip flexors', 'quads', 'core', 'calves'],
    benefits: [
      'Raises heart rate quickly',
      'Burns calories fast',
      'Improves hip flexor strength',
      'Enhances coordination',
      'Warm up or standalone cardio',
    ],
    instructions: [
      'Stand with feet hip-width apart',
      'Begin jogging in place',
      'Drive knees up toward chest',
      'Pump arms opposite to legs',
      'Move as fast as possible',
      'Land softly on balls of feet',
    ],
    duration: '30-60 seconds',
    caloriesBurn: '10 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,high-knees',
    tags: ['cardio', 'hiit', 'full-body', 'warm-up'],
  },
  {
    name: 'Side Plank',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['obliques', 'core', 'shoulders', 'hips'],
    benefits: [
      'Strengthens obliques specifically',
      'Improves lateral core stability',
      'Reduces risk of side injuries',
      'Improves balance',
      'No equipment needed',
    ],
    instructions: [
      'Lie on side with legs stacked',
      'Prop upper body on forearm',
      'Lift hips until body forms straight line',
      'Hold position without sagging',
      'Breathe steadily',
      'Switch sides after hold',
    ],
    duration: '20-40 seconds per side',
    caloriesBurn: '3 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,side-plank',
    tags: ['core', 'obliques', 'bodyweight', 'stability'],
  },
  {
    name: 'Skater Jumps',
    category: 'plyometric',
    difficulty: 'intermediate',
    targetMuscles: ['quads', 'glutes', 'calves', 'core'],
    benefits: [
      'Lateral explosive movement',
      'Burns calories quickly',
      'Improves agility and coordination',
      'Strengthens leg stabilizers',
      'Great for fat burning',
    ],
    instructions: [
      'Stand on right leg, left foot slightly off ground',
      'Jump laterally to the left',
      'Land on left leg, crossing right behind',
      'Immediately jump back to the right',
      'Keep core engaged throughout',
      'Land softly on each foot',
    ],
    duration: '30-45 seconds',
    caloriesBurn: '11 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,skater-jumps',
    tags: ['plyometric', 'cardio', 'lateral', 'agility'],
  },
  {
    name: 'Superman Hold',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['lower back', 'glutes', 'shoulders', 'hamstrings'],
    benefits: [
      'Strengthens lower back muscles',
      'Improves posture',
      'Balances core training',
      'Prevents back pain',
      'No equipment needed',
    ],
    instructions: [
      'Lie face down with arms extended forward',
      'Lift arms, chest, and legs off ground',
      'Hold position like flying superman',
      'Squeeze lower back and glutes',
      'Hold for 2-3 seconds',
      'Lower with control',
    ],
    duration: '3 sets of 10 reps (hold 3 sec each)',
    caloriesBurn: '3 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,superman-hold',
    tags: ['strength', 'back', 'posture', 'beginner'],
  },
  {
    name: 'Diamond Push-Ups',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['triceps', 'chest', 'shoulders', 'core'],
    benefits: [
      'Targets triceps intensely',
      'Builds arm strength',
      'Engages inner chest',
      'Variation of standard push-up',
      'No equipment needed',
    ],
    instructions: [
      'Start in push-up position',
      'Bring hands together forming diamond shape',
      'Lower chest toward hands',
      'Keep elbows close to body',
      'Push back up to starting position',
      'Maintain straight body line throughout',
    ],
    duration: '3 sets of 8-12 reps',
    caloriesBurn: '7 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,diamond-push-ups',
    tags: ['strength', 'triceps', 'upper-body', 'bodyweight'],
  },
  {
    name: 'Donkey Kicks',
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['glutes', 'core', 'hamstrings'],
    benefits: [
      'Isolates and activates glutes',
      'Improves hip mobility',
      'Great warm up for leg day',
      'No equipment needed',
      'Tones glutes effectively',
    ],
    instructions: [
      'Start on hands and knees table position',
      'Keep back flat and core engaged',
      'Kick right leg back and up toward ceiling',
      'Squeeze glute at top',
      'Lower leg back to start',
      'Repeat on both sides',
    ],
    duration: '3 sets of 15 reps each leg',
    caloriesBurn: '4 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,donkey-kicks',
    tags: ['strength', 'glutes', 'beginner', 'activation'],
  },
  {
    name: 'Dumbbell Lunges',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['quads', 'glutes', 'hamstrings', 'core'],
    benefits: [
      'Builds leg strength with added weight',
      'Improves balance and coordination',
      'Increases muscle mass in legs',
      'Functional movement',
      'Burns more calories than bodyweight',
    ],
    instructions: [
      'Hold dumbbells at sides',
      'Step forward with right leg',
      'Lower until both knees are at 90 degrees',
      'Push through front heel to return',
      'Alternate legs or complete one side at a time',
      'Keep torso upright throughout',
    ],
    duration: '3 sets of 10 reps each leg',
    caloriesBurn: '8 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,dumbbell-lunges',
    tags: ['strength', 'lower-body', 'dumbbell', 'balance'],
  },
  {
    name: 'Bicycle Kicks',
    category: 'cardio',
    difficulty: 'beginner',
    targetMuscles: ['hip flexors', 'quads', 'core', 'calves'],
    benefits: [
      'Great low impact cardio',
      'Improves hip mobility',
      'Strengthens hip flexors',
      'Good for warm up',
      'Easy on joints',
    ],
    instructions: [
      'Lie on back with legs raised',
      'Support upper body on elbows',
      'Pedal legs as if riding a bicycle',
      'Alternate bringing knees toward chest',
      'Keep movement controlled',
      'Breathe rhythmically',
    ],
    duration: '1-2 minutes',
    caloriesBurn: '5 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,bicycle-kicks',
    tags: ['cardio', 'low-impact', 'warm-up', 'mobility'],
  },
  {
    name: 'Farmer Walks',
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['core', 'forearms', 'traps', 'legs'],
    benefits: [
      'Builds grip strength',
      'Strengthens core dynamically',
      'Improves posture',
      'Functional carrying movement',
      'Full body conditioning',
    ],
    instructions: [
      'Hold heavy dumbbells or kettlebells at sides',
      'Stand tall with shoulders back',
      'Walk forward maintaining upright posture',
      'Take controlled steps',
      'Keep core engaged throughout',
      'Walk for distance or time',
    ],
    duration: '3 sets of 30-60 seconds',
    caloriesBurn: '6 per minute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?fitness,farmer-walks',
    tags: ['strength', 'grip', 'core', 'functional'],
  },
];
