export const foodsSeedData = [

  // ===== VEGETABLES =====
  {
    name: 'Lettuce',
    category: 'vegetable',
    benefits: ['Low calorie content', 'Contains vitamin A for eye health', 'Contains vitamin K for bone health', 'Supports hydration', 'Rich in antioxidants'],
    goodFor: ['weight loss', 'heart health', 'digestion', 'hydration'],
    nutrients: [{ name: 'Calories', amount: '15 per 100g' }, { name: 'Vitamin A', amount: '148% DV' }, { name: 'Vitamin K', amount: '126% DV' }, { name: 'Folate', amount: '18% DV' }],
    servingSuggestion: 'Use as salad base or in sandwiches',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,lettuce',
    tags: ['salad', 'green', 'low-calorie', 'hydration'],
  },
  {
    name: 'Spinach',
    category: 'vegetable',
    benefits: ['Packed with iron for blood health', 'Rich in vitamin K for bones', 'Contains antioxidants', 'Supports eye health with lutein', 'Low calorie and nutrient dense'],
    goodFor: ['weight loss', 'bone health', 'eye health', 'energy'],
    nutrients: [{ name: 'Calories', amount: '23 per 100g' }, { name: 'Iron', amount: '36% DV' }, { name: 'Vitamin K', amount: '604% DV' }, { name: 'Vitamin A', amount: '188% DV' }],
    servingSuggestion: 'Add to smoothies, salads, or saute as side dish',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,spinach',
    tags: ['iron', 'leafy-green', 'low-calorie', 'superfood'],
  },
  {
    name: 'Broccoli',
    category: 'vegetable',
    benefits: ['Rich in vitamin C and K', 'Contains sulforaphane for cancer prevention', 'High in fiber for digestion', 'Supports immune function', 'Anti-inflammatory properties'],
    goodFor: ['immunity', 'digestion', 'weight loss', 'bone health'],
    nutrients: [{ name: 'Calories', amount: '34 per 100g' }, { name: 'Vitamin C', amount: '135% DV' }, { name: 'Vitamin K', amount: '116% DV' }, { name: 'Fiber', amount: '2.6g' }],
    servingSuggestion: 'Steam, roast, or add to stir-fries',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,broccoli',
    tags: ['cruciferous', 'vitamin-c', 'fiber', 'anti-inflammatory'],
  },
  {
    name: 'Sweet Potato',
    category: 'vegetable',
    benefits: ['Rich in beta-carotene for eye health', 'Provides steady energy with complex carbs', 'High in fiber for digestion', 'Contains vitamin C for immunity', 'Natural anti-inflammatory'],
    goodFor: ['energy', 'digestion', 'immunity', 'workout'],
    nutrients: [{ name: 'Calories', amount: '86 per 100g' }, { name: 'Vitamin A', amount: '283% DV' }, { name: 'Fiber', amount: '3g' }, { name: 'Vitamin C', amount: '30% DV' }],
    servingSuggestion: 'Baked, roasted, or mashed as a healthy carb source',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,sweet-potato',
    tags: ['complex-carbs', 'vitamin-a', 'energy', 'anti-inflammatory'],
  },
  {
    name: 'Kale',
    category: 'vegetable',
    benefits: ['One of the most nutrient-dense foods', 'Rich in vitamins A, C, and K', 'Contains powerful antioxidants', 'Supports heart health', 'Anti-inflammatory properties'],
    goodFor: ['heart health', 'detox', 'bone health', 'weight loss'],
    nutrients: [{ name: 'Calories', amount: '49 per 100g' }, { name: 'Vitamin K', amount: '684% DV' }, { name: 'Vitamin C', amount: '200% DV' }, { name: 'Vitamin A', amount: '206% DV' }],
    servingSuggestion: 'Use in salads, smoothies, or bake into chips',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,kale',
    tags: ['superfood', 'leafy-green', 'antioxidants', 'nutrient-dense'],
  },
  {
    name: 'Carrots',
    category: 'vegetable',
    benefits: ['Excellent source of beta-carotene', 'Supports eye health and vision', 'Rich in fiber for digestion', 'Boosts immune system', 'Low calorie crunchy snack'],
    goodFor: ['eye health', 'immunity', 'digestion', 'skin health'],
    nutrients: [{ name: 'Calories', amount: '41 per 100g' }, { name: 'Vitamin A', amount: '334% DV' }, { name: 'Vitamin K', amount: '13% DV' }, { name: 'Fiber', amount: '2.8g' }],
    servingSuggestion: 'Eat raw with hummus, roast, or add to soups',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,carrots',
    tags: ['beta-carotene', 'eye-health', 'crunchy', 'snack'],
  },
  {
    name: 'Tomatoes',
    category: 'vegetable',
    benefits: ['Rich in lycopene for heart health', 'Contains vitamin C for immunity', 'Supports skin health', 'Low calorie and hydrating', 'May reduce cancer risk'],
    goodFor: ['heart health', 'skin health', 'immunity', 'weight loss'],
    nutrients: [{ name: 'Calories', amount: '18 per 100g' }, { name: 'Vitamin C', amount: '28% DV' }, { name: 'Lycopene', amount: '2573 mcg' }, { name: 'Potassium', amount: '237mg' }],
    servingSuggestion: 'Fresh in salads, cooked in sauces, or juiced',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,tomatoes',
    tags: ['lycopene', 'vitamin-c', 'salad', 'heart-health'],
  },
  {
    name: 'Cucumber',
    category: 'vegetable',
    benefits: ['Extremely hydrating (96% water)', 'Very low calorie', 'Contains antioxidants', 'Supports skin health', 'Aids digestion'],
    goodFor: ['hydration', 'weight loss', 'skin health', 'digestion'],
    nutrients: [{ name: 'Calories', amount: '15 per 100g' }, { name: 'Vitamin K', amount: '16% DV' }, { name: 'Magnesium', amount: '4% DV' }, { name: 'Potassium', amount: '147mg' }],
    servingSuggestion: 'Slice into salads, add to water, or eat as snack',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,cucumber',
    tags: ['hydration', 'low-calorie', 'salad', 'refreshing'],
  },
  {
    name: 'Bell Peppers',
    category: 'vegetable',
    benefits: ['Highest vitamin C content among vegetables', 'Rich in antioxidants', 'Supports eye health', 'Low calorie and colorful', 'Anti-inflammatory properties'],
    goodFor: ['immunity', 'eye health', 'weight loss', 'skin health'],
    nutrients: [{ name: 'Calories', amount: '31 per 100g' }, { name: 'Vitamin C', amount: '213% DV' }, { name: 'Vitamin A', amount: '47% DV' }, { name: 'Fiber', amount: '2.1g' }],
    servingSuggestion: 'Eat raw with dips, stuff with rice, or stir-fry',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,bell-peppers',
    tags: ['vitamin-c', 'colorful', 'crunchy', 'low-calorie'],
  },
  {
    name: 'Cauliflower',
    category: 'vegetable',
    benefits: ['Low carb alternative to grains', 'Rich in choline for brain health', 'Contains sulforaphane', 'High in fiber', 'Versatile cooking ingredient'],
    goodFor: ['weight loss', 'brain health', 'digestion', 'low-carb'],
    nutrients: [{ name: 'Calories', amount: '25 per 100g' }, { name: 'Vitamin C', amount: '77% DV' }, { name: 'Vitamin K', amount: '20% DV' }, { name: 'Fiber', amount: '2g' }],
    servingSuggestion: 'Rice it, roast it, mash it, or make pizza crust',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,cauliflower',
    tags: ['low-carb', 'versatile', 'cruciferous', 'keto'],
  },
  {
    name: 'Onions',
    category: 'vegetable',
    benefits: ['Contains powerful antioxidants', 'Supports heart health', 'Anti-inflammatory properties', 'May improve blood sugar control', 'Adds flavor without calories'],
    goodFor: ['heart health', 'immunity', 'blood sugar', 'flavor'],
    nutrients: [{ name: 'Calories', amount: '40 per 100g' }, { name: 'Vitamin C', amount: '12% DV' }, { name: 'Fiber', amount: '1.7g' }, { name: 'Antioxidants', amount: 'Quercetin' }],
    servingSuggestion: 'Saute as base for cooking, or add raw to salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,onions',
    tags: ['flavor', 'antioxidants', 'heart-health', 'cooking-base'],
  },
  {
    name: 'Garlic',
    category: 'vegetable',
    benefits: ['Potent medicinal properties', 'Boosts immune system', 'Supports heart health', 'Anti-inflammatory and antibacterial', 'May reduce blood pressure'],
    goodFor: ['immunity', 'heart health', 'blood pressure', 'flavor'],
    nutrients: [{ name: 'Calories', amount: '149 per 100g' }, { name: 'Vitamin C', amount: '31% DV' }, { name: 'Vitamin B6', amount: '62% DV' }, { name: 'Manganese', amount: '73% DV' }],
    servingSuggestion: 'Add to almost any savory dish for flavor',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,garlic',
    tags: ['immune-booster', 'antibacterial', 'flavor', 'heart-health'],
  },
  {
    name: 'Zucchini',
    category: 'vegetable',
    benefits: ['Very low calorie', 'Rich in antioxidants', 'Supports digestion with fiber', 'Contains vitamin C and B6', 'Versatile low-carb substitute'],
    goodFor: ['weight loss', 'digestion', 'low-carb', 'hydration'],
    nutrients: [{ name: 'Calories', amount: '17 per 100g' }, { name: 'Vitamin C', amount: '20% DV' }, { name: 'Vitamin B6', amount: '11% DV' }, { name: 'Fiber', amount: '1g' }],
    servingSuggestion: 'Spiralize into noodles, grill, or add to stir-fry',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,zucchini',
    tags: ['low-calorie', 'low-carb', 'zoodles', 'versatile'],
  },
  {
    name: 'Asparagus',
    category: 'vegetable',
    benefits: ['Rich in folate for cell growth', 'Natural diuretic reduces bloating', 'Contains vitamin K for bones', 'High in antioxidants', 'Low calorie and nutrient dense'],
    goodFor: ['digestion', 'bone health', 'weight loss', 'pregnancy'],
    nutrients: [{ name: 'Calories', amount: '20 per 100g' }, { name: 'Vitamin K', amount: '57% DV' }, { name: 'Folate', amount: '34% DV' }, { name: 'Fiber', amount: '2.1g' }],
    servingSuggestion: 'Grill, roast, or steam with lemon and olive oil',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,asparagus',
    tags: ['folate', 'low-calorie', 'diuretic', 'spring-vegetable'],
  },
  {
    name: 'Green Beans',
    category: 'vegetable',
    benefits: ['Good source of plant protein', 'Rich in vitamin K and C', 'Contains fiber for digestion', 'Supports bone health', 'Low calorie and filling'],
    goodFor: ['weight loss', 'bone health', 'digestion', 'plant-protein'],
    nutrients: [{ name: 'Calories', amount: '31 per 100g' }, { name: 'Vitamin C', amount: '16% DV' }, { name: 'Vitamin K', amount: '14% DV' }, { name: 'Fiber', amount: '2.7g' }],
    servingSuggestion: 'Steam, saute with garlic, or add to casseroles',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,green-beans',
    tags: ['fiber', 'vitamin-k', 'side-dish', 'low-calorie'],
  },
  {
    name: 'Mushrooms',
    category: 'vegetable',
    benefits: ['Only plant source of vitamin D', 'Rich in B vitamins for energy', 'Contains immune-boosting beta-glucans', 'Low calorie and savory', 'Antioxidant properties'],
    goodFor: ['immunity', 'energy', 'weight loss', 'bone health'],
    nutrients: [{ name: 'Calories', amount: '22 per 100g' }, { name: 'Vitamin D', amount: 'Varies' }, { name: 'Vitamin B6', amount: '11% DV' }, { name: 'Selenium', amount: '26% DV' }],
    servingSuggestion: 'Saute, grill, or add to omelettes and stir-fries',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,mushrooms',
    tags: ['vitamin-d', 'umami', 'immune-booster', 'low-calorie'],
  },

  // ===== FRUITS =====
  {
    name: 'Banana',
    category: 'fruit',
    benefits: ['Rich in potassium for heart health', 'Provides quick energy', 'Supports digestion with fiber', 'Contains vitamin B6 for brain health', 'Natural pre-workout snack'],
    goodFor: ['energy', 'heart health', 'digestion', 'workout'],
    nutrients: [{ name: 'Calories', amount: '89 per 100g' }, { name: 'Potassium', amount: '358mg' }, { name: 'Vitamin B6', amount: '33% DV' }, { name: 'Vitamin C', amount: '14% DV' }],
    servingSuggestion: 'Eat raw, blend in smoothies, or add to oatmeal',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,banana',
    tags: ['fruit', 'potassium', 'energy', 'pre-workout'],
  },
  {
    name: 'Avocado',
    category: 'fruit',
    benefits: ['Rich in healthy monounsaturated fats', 'Supports heart health', 'Contains fiber for digestion', 'Rich in vitamin K and folate', 'Helps absorb nutrients from other foods'],
    goodFor: ['heart health', 'weight management', 'skin health', 'digestion'],
    nutrients: [{ name: 'Calories', amount: '160 per 100g' }, { name: 'Healthy Fats', amount: '15g' }, { name: 'Fiber', amount: '6.7g' }, { name: 'Vitamin K', amount: '26% DV' }],
    servingSuggestion: 'Add to salads, toast, or make guacamole',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,avocado',
    tags: ['healthy-fats', 'fiber', 'heart', 'superfood'],
  },
  {
    name: 'Blueberries',
    category: 'fruit',
    benefits: ['Packed with antioxidants (anthocyanins)', 'Supports brain health and memory', 'Anti-inflammatory properties', 'Rich in vitamin C', 'Low calorie and nutrient dense'],
    goodFor: ['brain health', 'immunity', 'weight loss', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '57 per 100g' }, { name: 'Vitamin C', amount: '16% DV' }, { name: 'Vitamin K', amount: '24% DV' }, { name: 'Fiber', amount: '2.4g' }],
    servingSuggestion: 'Add to smoothies, oatmeal, or eat as snack',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,blueberries',
    tags: ['antioxidants', 'brain', 'fruit', 'superfood'],
  },
  {
    name: 'Apples',
    category: 'fruit',
    benefits: ['Rich in fiber for digestion', 'Contains vitamin C for immunity', 'Low calorie and filling', 'Supports heart health', 'Natural tooth cleaner'],
    goodFor: ['digestion', 'weight loss', 'heart health', 'immunity'],
    nutrients: [{ name: 'Calories', amount: '52 per 100g' }, { name: 'Fiber', amount: '2.4g' }, { name: 'Vitamin C', amount: '14% DV' }, { name: 'Antioxidants', amount: 'Quercetin' }],
    servingSuggestion: 'Eat fresh, bake with cinnamon, or add to salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,apples',
    tags: ['fiber', 'snack', 'heart-health', 'portable'],
  },
  {
    name: 'Oranges',
    category: 'fruit',
    benefits: ['Excellent source of vitamin C', 'Boosts immune system', 'Contains fiber for digestion', 'Supports skin health with collagen', 'Hydrating and refreshing'],
    goodFor: ['immunity', 'skin health', 'digestion', 'hydration'],
    nutrients: [{ name: 'Calories', amount: '47 per 100g' }, { name: 'Vitamin C', amount: '88% DV' }, { name: 'Fiber', amount: '2.4g' }, { name: 'Folate', amount: '10% DV' }],
    servingSuggestion: 'Eat fresh, juice, or add to fruit salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,oranges',
    tags: ['vitamin-c', 'citrus', 'immunity', 'refreshing'],
  },
  {
    name: 'Strawberries',
    category: 'fruit',
    benefits: ['Packed with vitamin C', 'Contains antioxidants for skin', 'Low calorie and naturally sweet', 'Supports heart health', 'Anti-inflammatory properties'],
    goodFor: ['skin health', 'immunity', 'weight loss', 'heart health'],
    nutrients: [{ name: 'Calories', amount: '32 per 100g' }, { name: 'Vitamin C', amount: '98% DV' }, { name: 'Fiber', amount: '2g' }, { name: 'Manganese', amount: '19% DV' }],
    servingSuggestion: 'Fresh as snack, sliced in yogurt, or blended in smoothies',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,strawberries',
    tags: ['vitamin-c', 'berries', 'low-calorie', 'sweet'],
  },
  {
    name: 'Grapes',
    category: 'fruit',
    benefits: ['Contains resveratrol for heart health', 'Rich in vitamin C and K', 'Hydrating with high water content', 'Contains antioxidants', 'Natural quick energy source'],
    goodFor: ['heart health', 'hydration', 'energy', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '69 per 100g' }, { name: 'Vitamin K', amount: '18% DV' }, { name: 'Vitamin C', amount: '5% DV' }, { name: 'Resveratrol', amount: 'Present' }],
    servingSuggestion: 'Eat fresh, freeze for cold snack, or add to fruit salad',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,grapes',
    tags: ['resveratrol', 'fruit', 'snack', 'hydrating'],
  },
  {
    name: 'Pineapple',
    category: 'fruit',
    benefits: ['Contains bromelain for digestion', 'Rich in vitamin C and manganese', 'Anti-inflammatory properties', 'Supports immune function', 'Natural sweetness'],
    goodFor: ['digestion', 'immunity', 'skin health', 'anti-inflammatory'],
    nutrients: [{ name: 'Calories', amount: '50 per 100g' }, { name: 'Vitamin C', amount: '79% DV' }, { name: 'Manganese', amount: '109% DV' }, { name: 'Bromelain', amount: 'Present' }],
    servingSuggestion: 'Fresh chunks, grilled slices, or blended in smoothies',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,pineapple',
    tags: ['bromelain', 'tropical', 'vitamin-c', 'digestive'],
  },
  {
    name: 'Mango',
    category: 'fruit',
    benefits: ['Rich in vitamin C and A', 'Contains digestive enzymes', 'Supports eye health', 'Boosts immune system', 'Natural energy source'],
    goodFor: ['immunity', 'eye health', 'digestion', 'energy'],
    nutrients: [{ name: 'Calories', amount: '60 per 100g' }, { name: 'Vitamin C', amount: '67% DV' }, { name: 'Vitamin A', amount: '10% DV' }, { name: 'Folate', amount: '11% DV' }],
    servingSuggestion: 'Fresh slices, in smoothies, or as salsa ingredient',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,mango',
    tags: ['tropical', 'vitamin-c', 'sweet', 'summer'],
  },
  {
    name: 'Watermelon',
    category: 'fruit',
    benefits: ['Extremely hydrating (92% water)', 'Contains lycopene for heart health', 'Low calorie and refreshing', 'Contains vitamins A and C', 'Natural post-workout hydration'],
    goodFor: ['hydration', 'weight loss', 'heart health', 'workout recovery'],
    nutrients: [{ name: 'Calories', amount: '30 per 100g' }, { name: 'Vitamin C', amount: '21% DV' }, { name: 'Vitamin A', amount: '18% DV' }, { name: 'Lycopene', amount: '4532 mcg' }],
    servingSuggestion: 'Chilled slices, cubed in salads, or blended juice',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,watermelon',
    tags: ['hydration', 'low-calorie', 'summer', 'refreshing'],
  },
  {
    name: 'Pomegranate',
    category: 'fruit',
    benefits: ['Packed with powerful antioxidants', 'Supports heart health', 'Anti-inflammatory properties', 'May improve memory', 'Rich in vitamin C and K'],
    goodFor: ['heart health', 'brain health', 'antioxidants', 'immunity'],
    nutrients: [{ name: 'Calories', amount: '83 per 100g' }, { name: 'Vitamin C', amount: '17% DV' }, { name: 'Vitamin K', amount: '24% DV' }, { name: 'Fiber', amount: '4g' }],
    servingSuggestion: 'Sprinkle seeds on salads, yogurt, or eat as is',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,pomegranate',
    tags: ['antioxidants', 'superfood', 'heart-health', 'seeds'],
  },
  {
    name: 'Papaya',
    category: 'fruit',
    benefits: ['Contains papain enzyme for digestion', 'Rich in vitamin C and A', 'Anti-inflammatory properties', 'Supports skin health', 'Boosts immune system'],
    goodFor: ['digestion', 'skin health', 'immunity', 'anti-inflammatory'],
    nutrients: [{ name: 'Calories', amount: '43 per 100g' }, { name: 'Vitamin C', amount: '103% DV' }, { name: 'Vitamin A', amount: '22% DV' }, { name: 'Folate', amount: '10% DV' }],
    servingSuggestion: 'Fresh slices with lime juice, or blended in smoothies',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,papaya',
    tags: ['digestive', 'tropical', 'vitamin-c', 'papain'],
  },
  {
    name: 'Kiwi',
    category: 'fruit',
    benefits: ['More vitamin C than oranges', 'Supports digestion with actinidin', 'Rich in fiber for gut health', 'Supports immune function', 'Contains serotonin for sleep'],
    goodFor: ['immunity', 'digestion', 'sleep', 'skin health'],
    nutrients: [{ name: 'Calories', amount: '61 per 100g' }, { name: 'Vitamin C', amount: '154% DV' }, { name: 'Vitamin K', amount: '34% DV' }, { name: 'Fiber', amount: '3g' }],
    servingSuggestion: 'Slice and eat fresh, add to yogurt or fruit salad',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,kiwi',
    tags: ['vitamin-c', 'digestive', 'green', 'sleep'],
  },

  // ===== PROTEIN =====
  {
    name: 'Eggs',
    category: 'protein',
    benefits: ['High quality complete protein', 'Contains choline for brain health', 'Supports muscle building and repair', 'Rich in vitamin D and B12', 'Promotes satiety'],
    goodFor: ['muscle gain', 'weight loss', 'brain health', 'breakfast'],
    nutrients: [{ name: 'Calories', amount: '155 per 100g' }, { name: 'Protein', amount: '13g' }, { name: 'Vitamin D', amount: '15% DV' }, { name: 'Choline', amount: '125mg' }],
    servingSuggestion: 'Boiled, scrambled, poached, or in omelettes',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,eggs',
    tags: ['protein', 'breakfast', 'muscle', 'satiety'],
  },
  {
    name: 'Chicken Breast',
    category: 'protein',
    benefits: ['Lean source of high quality protein', 'Supports muscle growth and repair', 'Low in fat when skinless', 'Rich in B vitamins for energy', 'Keeps you full for longer'],
    goodFor: ['muscle gain', 'weight loss', 'meal prep', 'recovery'],
    nutrients: [{ name: 'Calories', amount: '165 per 100g' }, { name: 'Protein', amount: '31g' }, { name: 'Fat', amount: '3.6g' }, { name: 'Vitamin B6', amount: '25% DV' }],
    servingSuggestion: 'Grill, bake, or pan-sear with vegetables',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,chicken-breast',
    tags: ['protein', 'lean', 'muscle', 'meal-prep'],
  },
  {
    name: 'Salmon',
    category: 'protein',
    benefits: ['Rich in omega-3 fatty acids for heart and brain', 'High quality protein source', 'Contains vitamin D and B12', 'Supports brain function and mood', 'Anti-inflammatory properties'],
    goodFor: ['heart health', 'brain health', 'mood', 'muscle gain'],
    nutrients: [{ name: 'Calories', amount: '208 per 100g' }, { name: 'Protein', amount: '20g' }, { name: 'Omega-3', amount: '2.3g' }, { name: 'Vitamin D', amount: '66% DV' }],
    servingSuggestion: 'Grill, bake, or pan-sear with herbs and lemon',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,salmon',
    tags: ['omega-3', 'protein', 'heart', 'brain'],
  },
  {
    name: 'Tuna',
    category: 'protein',
    benefits: ['Excellent lean protein source', 'Rich in omega-3 fatty acids', 'Contains selenium for thyroid', 'Supports muscle maintenance', 'Convenient and affordable'],
    goodFor: ['muscle gain', 'weight loss', 'heart health', 'meal prep'],
    nutrients: [{ name: 'Calories', amount: '184 per 100g' }, { name: 'Protein', amount: '30g' }, { name: 'Omega-3', amount: '1.8g' }, { name: 'Selenium', amount: '194% DV' }],
    servingSuggestion: 'Canned in salads, grilled steaks, or sushi grade',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,tuna',
    tags: ['protein', 'omega-3', 'convenient', 'seafood'],
  },
  {
    name: 'Lean Beef',
    category: 'protein',
    benefits: ['Rich in iron for blood health', 'Complete protein for muscle growth', 'Contains zinc for immunity', 'High in B12 for energy', 'Contains creatine for performance'],
    goodFor: ['muscle gain', 'energy', 'immunity', 'iron'],
    nutrients: [{ name: 'Calories', amount: '250 per 100g' }, { name: 'Protein', amount: '26g' }, { name: 'Iron', amount: '15% DV' }, { name: 'Vitamin B12', amount: '101% DV' }],
    servingSuggestion: 'Grilled steak, stir-fry strips, or ground in recipes',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,lean-beef',
    tags: ['protein', 'iron', 'red-meat', 'muscle'],
  },
  {
    name: 'Turkey Breast',
    category: 'protein',
    benefits: ['Very lean protein source', 'Rich in B vitamins', 'Contains tryptophan for sleep', 'Low in saturated fat', 'Versatile for meals'],
    goodFor: ['muscle gain', 'weight loss', 'meal prep', 'sleep'],
    nutrients: [{ name: 'Calories', amount: '135 per 100g' }, { name: 'Protein', amount: '29g' }, { name: 'Fat', amount: '1g' }, { name: 'Vitamin B6', amount: '27% DV' }],
    servingSuggestion: 'Roasted slices, ground turkey dishes, or deli meat',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,turkey-breast',
    tags: ['lean', 'protein', 'poultry', 'low-fat'],
  },
  {
    name: 'Shrimp',
    category: 'protein',
    benefits: ['Low calorie high protein option', 'Rich in selenium and iodine', 'Contains astaxanthin antioxidant', 'Quick cooking time', 'Versatile in dishes'],
    goodFor: ['weight loss', 'muscle gain', 'immunity', 'seafood'],
    nutrients: [{ name: 'Calories', amount: '99 per 100g' }, { name: 'Protein', amount: '24g' }, { name: 'Selenium', amount: '66% DV' }, { name: 'Vitamin B12', amount: '21% DV' }],
    servingSuggestion: 'Grill, saute with garlic, or add to pasta and salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,shrimp',
    tags: ['low-calorie', 'protein', 'seafood', 'quick-cook'],
  },
  {
    name: 'Tofu',
    category: 'protein',
    benefits: ['Complete plant protein', 'Contains iron and calcium', 'Low in calories and versatile', 'Contains isoflavones for heart health', 'Absorbs flavors well'],
    goodFor: ['muscle gain', 'weight loss', 'heart health', 'plant-based'],
    nutrients: [{ name: 'Calories', amount: '76 per 100g' }, { name: 'Protein', amount: '8g' }, { name: 'Calcium', amount: '35% DV' }, { name: 'Iron', amount: '29% DV' }],
    servingSuggestion: 'Stir-fry, grill, blend into smoothies, or scramble',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,tofu',
    tags: ['plant-protein', 'vegan', 'versatile', 'calcium'],
  },
  {
    name: 'Greek Yogurt',
    category: 'dairy',
    benefits: ['High in protein for muscle repair', 'Contains probiotics for gut health', 'Rich in calcium for bones', 'Supports digestion', 'Helps with satiety'],
    goodFor: ['digestion', 'muscle gain', 'weight loss', 'bone health'],
    nutrients: [{ name: 'Calories', amount: '97 per 100g' }, { name: 'Protein', amount: '10g' }, { name: 'Calcium', amount: '11% DV' }, { name: 'Probiotics', amount: 'Live cultures' }],
    servingSuggestion: 'Eat with fruits, nuts, or use as sour cream substitute',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,greek-yogurt',
    tags: ['protein', 'probiotics', 'breakfast', 'snack'],
  },
  {
    name: 'Cottage Cheese',
    category: 'dairy',
    benefits: ['Very high in casein protein', 'Slow-digesting protein for muscle', 'Rich in calcium and B12', 'Low fat options available', 'Promotes fullness overnight'],
    goodFor: ['muscle gain', 'weight loss', 'bone health', 'bedtime snack'],
    nutrients: [{ name: 'Calories', amount: '98 per 100g' }, { name: 'Protein', amount: '11g' }, { name: 'Calcium', amount: '8% DV' }, { name: 'Vitamin B12', amount: '14% DV' }],
    servingSuggestion: 'Eat with fruit, on toast, or in savory dishes',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,cottage-cheese',
    tags: ['casein', 'protein', 'dairy', 'bedtime'],
  },
  {
    name: 'Milk',
    category: 'dairy',
    benefits: ['Rich in calcium for strong bones', 'Complete protein source', 'Contains vitamin D', 'Supports muscle recovery', 'Natural hydration'],
    goodFor: ['bone health', 'muscle gain', 'hydration', 'recovery'],
    nutrients: [{ name: 'Calories', amount: '66 per 100ml' }, { name: 'Protein', amount: '3.2g' }, { name: 'Calcium', amount: '21% DV' }, { name: 'Vitamin D', amount: '15% DV' }],
    servingSuggestion: 'Drink plain, add to smoothies, or use in cooking',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,milk',
    tags: ['calcium', 'dairy', 'protein', 'hydration'],
  },

  // ===== GRAINS =====
  {
    name: 'Oats',
    category: 'grain',
    benefits: ['High in fiber for digestive health', 'Helps lower cholesterol', 'Provides sustained energy', 'Rich in antioxidants', 'Supports weight management'],
    goodFor: ['weight loss', 'heart health', 'digestion', 'energy'],
    nutrients: [{ name: 'Calories', amount: '389 per 100g' }, { name: 'Fiber', amount: '10.6g' }, { name: 'Protein', amount: '16.9g' }, { name: 'Iron', amount: '20% DV' }],
    servingSuggestion: 'Have as oatmeal for breakfast with fruits',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,oats',
    tags: ['breakfast', 'fiber', 'whole-grain', 'energy'],
  },
  {
    name: 'Quinoa',
    category: 'grain',
    benefits: ['Complete plant protein with all amino acids', 'High in fiber for digestion', 'Gluten-free', 'Rich in iron and magnesium', 'Supports weight management'],
    goodFor: ['muscle gain', 'weight loss', 'digestion', 'energy'],
    nutrients: [{ name: 'Calories', amount: '120 per 100g' }, { name: 'Protein', amount: '4.4g' }, { name: 'Fiber', amount: '2.8g' }, { name: 'Iron', amount: '8% DV' }],
    servingSuggestion: 'Use as rice substitute or in salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,quinoa',
    tags: ['protein', 'gluten-free', 'whole-grain', 'complete-protein'],
  },
  {
    name: 'Brown Rice',
    category: 'grain',
    benefits: ['Whole grain with fiber intact', 'Provides steady energy release', 'Contains magnesium and B vitamins', 'Supports heart health', 'Better than white rice for blood sugar'],
    goodFor: ['energy', 'heart health', 'digestion', 'weight management'],
    nutrients: [{ name: 'Calories', amount: '111 per 100g' }, { name: 'Fiber', amount: '1.8g' }, { name: 'Magnesium', amount: '11% DV' }, { name: 'Vitamin B6', amount: '7% DV' }],
    servingSuggestion: 'Serve with stir-fries, curries, or as a side dish',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,brown-rice',
    tags: ['whole-grain', 'fiber', 'complex-carbs', 'staple'],
  },
  {
    name: 'Whole Wheat Bread',
    category: 'grain',
    benefits: ['Higher fiber than white bread', 'Contains B vitamins for energy', 'Provides complex carbohydrates', 'Supports digestive health', 'More nutrients than refined bread'],
    goodFor: ['energy', 'digestion', 'weight management'],
    nutrients: [{ name: 'Calories', amount: '247 per 100g' }, { name: 'Fiber', amount: '7g' }, { name: 'Protein', amount: '13g' }, { name: 'Iron', amount: '10% DV' }],
    servingSuggestion: 'Use for toast, sandwiches, or French toast',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,whole-wheat-bread',
    tags: ['whole-grain', 'fiber', 'staple', 'sandwich'],
  },
  {
    name: 'Barley',
    category: 'grain',
    benefits: ['Very high fiber content', 'Helps lower cholesterol', 'Provides steady energy', 'Rich in selenium', 'Supports blood sugar control'],
    goodFor: ['heart health', 'digestion', 'blood sugar', 'energy'],
    nutrients: [{ name: 'Calories', amount: '123 per 100g' }, { name: 'Fiber', amount: '3.8g' }, { name: 'Selenium', amount: '24% DV' }, { name: 'Magnesium', amount: '12% DV' }],
    servingSuggestion: 'Add to soups, stews, or use as a rice alternative',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,barley',
    tags: ['fiber', 'whole-grain', 'soup', 'heart-health'],
  },
  {
    name: 'Oatmeal',
    category: 'grain',
    benefits: ['Warm and comforting breakfast', 'Beta-glucan fiber lowers cholesterol', 'Provides long-lasting energy', 'Can be customized with toppings', 'Affordable and filling'],
    goodFor: ['heart health', 'weight loss', 'breakfast', 'energy'],
    nutrients: [{ name: 'Calories', amount: '71 per 100g cooked' }, { name: 'Fiber', amount: '1.7g' }, { name: 'Protein', amount: '2.5g' }, { name: 'Iron', amount: '4% DV' }],
    servingSuggestion: 'Top with fruits, nuts, seeds, and a drizzle of honey',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,oatmeal',
    tags: ['breakfast', 'fiber', 'warm', 'customizable'],
  },

  // ===== NUTS & SEEDS =====
  {
    name: 'Almonds',
    category: 'nuts',
    benefits: ['Rich in vitamin E for skin health', 'Contains healthy fats for heart', 'High in magnesium for muscle function', 'Supports weight management', 'Provides antioxidants'],
    goodFor: ['heart health', 'skin health', 'weight management', 'snack'],
    nutrients: [{ name: 'Calories', amount: '579 per 100g' }, { name: 'Vitamin E', amount: '171% DV' }, { name: 'Magnesium', amount: '75% DV' }, { name: 'Healthy Fats', amount: '49g' }],
    servingSuggestion: 'Handful as snack, or add to oatmeal and salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,almonds',
    tags: ['nuts', 'vitamin-e', 'healthy-fats', 'snack'],
  },
  {
    name: 'Walnuts',
    category: 'nuts',
    benefits: ['Highest omega-3 among nuts', 'Supports brain health', 'Anti-inflammatory properties', 'Rich in antioxidants', 'May improve heart health'],
    goodFor: ['brain health', 'heart health', 'mood', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '654 per 100g' }, { name: 'Omega-3', amount: '9g' }, { name: 'Protein', amount: '15g' }, { name: 'Magnesium', amount: '45% DV' }],
    servingSuggestion: 'Add to salads, oatmeal, or eat as snack',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,walnuts',
    tags: ['omega-3', 'brain', 'nuts', 'antioxidants'],
  },
  {
    name: 'Cashews',
    category: 'nuts',
    benefits: ['Creamy texture and rich flavor', 'Contains iron and zinc', 'Good source of magnesium', 'Supports bone health', 'Heart-healthy monounsaturated fats'],
    goodFor: ['bone health', 'energy', 'heart health', 'snack'],
    nutrients: [{ name: 'Calories', amount: '553 per 100g' }, { name: 'Iron', amount: '37% DV' }, { name: 'Magnesium', amount: '73% DV' }, { name: 'Zinc', amount: '28% DV' }],
    servingSuggestion: 'Handful as snack, or make creamy sauces',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,cashews',
    tags: ['nuts', 'creamy', 'magnesium', 'snack'],
  },
  {
    name: 'Chia Seeds',
    category: 'seeds',
    benefits: ['Packed with omega-3 fatty acids', 'High fiber expands in stomach', 'Contains protein and calcium', 'Supports digestion', 'Gel forms healthy pudding'],
    goodFor: ['digestion', 'heart health', 'weight loss', 'energy'],
    nutrients: [{ name: 'Calories', amount: '486 per 100g' }, { name: 'Fiber', amount: '34g' }, { name: 'Omega-3', amount: '17.6g' }, { name: 'Calcium', amount: '25% DV' }],
    servingSuggestion: 'Soak in liquid for pudding, add to smoothies',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,chia-seeds',
    tags: ['omega-3', 'fiber', 'superfood', 'pudding'],
  },
  {
    name: 'Flax Seeds',
    category: 'seeds',
    benefits: ['Rich in omega-3 and lignans', 'Supports digestive health', 'May help lower cholesterol', 'Contains fiber for fullness', 'Good source of magnesium'],
    goodFor: ['digestion', 'heart health', 'weight loss', 'hormone balance'],
    nutrients: [{ name: 'Calories', amount: '534 per 100g' }, { name: 'Fiber', amount: '27g' }, { name: 'Omega-3', amount: '22.8g' }, { name: 'Magnesium', amount: '36% DV' }],
    servingSuggestion: 'Grind and add to oatmeal, smoothies, or baking',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,flax-seeds',
    tags: ['omega-3', 'fiber', 'seeds', 'digestion'],
  },
  {
    name: 'Pumpkin Seeds',
    category: 'seeds',
    benefits: ['Rich in magnesium for sleep', 'Contains zinc for immunity', 'High in antioxidants', 'Good source of plant protein', 'Supports prostate health'],
    goodFor: ['sleep', 'immunity', 'energy', 'snack'],
    nutrients: [{ name: 'Calories', amount: '559 per 100g' }, { name: 'Magnesium', amount: '150% DV' }, { name: 'Zinc', amount: '44% DV' }, { name: 'Protein', amount: '30g' }],
    servingSuggestion: 'Roasted as snack, or sprinkle on salads and oatmeal',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,pumpkin-seeds',
    tags: ['magnesium', 'zinc', 'seeds', 'sleep'],
  },
  {
    name: 'Peanut Butter',
    category: 'nuts',
    benefits: ['Good source of protein and healthy fats', 'Provides sustained energy', 'Contains vitamin E and B3', 'Affordable protein source', 'Satisfies cravings'],
    goodFor: ['muscle gain', 'energy', 'weight management', 'snack'],
    nutrients: [{ name: 'Calories', amount: '588 per 100g' }, { name: 'Protein', amount: '25g' }, { name: 'Healthy Fats', amount: '50g' }, { name: 'Vitamin E', amount: '45% DV' }],
    servingSuggestion: 'Spread on toast, add to smoothies, or eat with apple slices',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,peanut-butter',
    tags: ['protein', 'healthy-fats', 'snack', 'spread'],
  },

  // ===== LEGUMES =====
  {
    name: 'Black Beans',
    category: 'legumes',
    benefits: ['Excellent plant protein source', 'High in fiber for digestion', 'Rich in iron and folate', 'Supports heart health', 'Helps stabilize blood sugar'],
    goodFor: ['heart health', 'digestion', 'blood sugar', 'plant-protein'],
    nutrients: [{ name: 'Calories', amount: '132 per 100g' }, { name: 'Fiber', amount: '8.7g' }, { name: 'Protein', amount: '8.9g' }, { name: 'Folate', amount: '31% DV' }],
    servingSuggestion: 'Add to burritos, soups, salads, or make veggie burgers',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,black-beans',
    tags: ['legumes', 'fiber', 'plant-protein', 'iron'],
  },
  {
    name: 'Lentils',
    category: 'legumes',
    benefits: ['Quick cooking legume', 'High in protein and fiber', 'Rich in iron for energy', 'Supports heart health', 'Very affordable protein source'],
    goodFor: ['heart health', 'energy', 'weight loss', 'plant-protein'],
    nutrients: [{ name: 'Calories', amount: '116 per 100g' }, { name: 'Fiber', amount: '7.9g' }, { name: 'Protein', amount: '9g' }, { name: 'Iron', amount: '17% DV' }],
    servingSuggestion: 'Use in soups, stews, curries, or salads',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,lentils',
    tags: ['legumes', 'protein', 'fiber', 'affordable'],
  },
  {
    name: 'Chickpeas',
    category: 'legumes',
    benefits: ['Excellent plant protein source', 'High in fiber for fullness', 'Rich in folate and iron', 'Versatile in many cuisines', 'Supports blood sugar control'],
    goodFor: ['weight loss', 'digestion', 'plant-protein', 'energy'],
    nutrients: [{ name: 'Calories', amount: '139 per 100g' }, { name: 'Fiber', amount: '7.6g' }, { name: 'Protein', amount: '7.2g' }, { name: 'Iron', amount: '14% DV' }],
    servingSuggestion: 'Hummus, salads, curries, or roasted for snack',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,chickpeas',
    tags: ['legumes', 'protein', 'hummus', 'fiber'],
  },
  {
    name: 'Edamame',
    category: 'legumes',
    benefits: ['Complete plant protein with all amino acids', 'Rich in fiber and folate', 'Contains vitamin K for bones', 'Supports heart health', 'Low calorie and filling'],
    goodFor: ['muscle gain', 'weight loss', 'bone health', 'plant-protein'],
    nutrients: [{ name: 'Calories', amount: '122 per 100g' }, { name: 'Protein', amount: '11g' }, { name: 'Fiber', amount: '5.2g' }, { name: 'Vitamin K', amount: '36% DV' }],
    servingSuggestion: 'Steamed with salt as appetizer or snack',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,edamame',
    tags: ['soy', 'plant-protein', 'snack', 'complete-protein'],
  },

  // ===== BEVERAGES =====
  {
    name: 'Water',
    category: 'beverage',
    benefits: ['Essential for hydration', 'Supports all bodily functions', 'Helps with weight management', 'Improves skin health', 'Boosts energy and brain function'],
    goodFor: ['hydration', 'weight loss', 'skin health', 'energy'],
    nutrients: [{ name: 'Calories', amount: '0' }, { name: 'Hydration', amount: 'Essential' }],
    servingSuggestion: 'Drink 8-10 glasses daily',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,water',
    tags: ['hydration', 'essential', 'zero-calorie'],
  },
  {
    name: 'Green Tea',
    category: 'beverage',
    benefits: ['Rich in antioxidants (catechins)', 'Boosts metabolism', 'Supports heart health', 'Contains L-theanine for calm focus', 'May aid weight loss'],
    goodFor: ['weight loss', 'heart health', 'focus', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '1 per cup' }, { name: 'Caffeine', amount: '28mg' }, { name: 'Antioxidants', amount: 'EGCG' }],
    servingSuggestion: 'Brew 2-3 minutes in hot water, drink plain',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,green-tea',
    tags: ['antioxidants', 'metabolism', 'tea', 'caffeine'],
  },
  {
    name: 'Lemon Water',
    category: 'beverage',
    benefits: ['Vitamin C boost for immunity', 'Aids digestion', 'Hydrating and refreshing', 'Supports skin health', 'Alkalizing effect on body'],
    goodFor: ['hydration', 'immunity', 'digestion', 'skin health'],
    nutrients: [{ name: 'Calories', amount: '6 per glass' }, { name: 'Vitamin C', amount: '18% DV' }],
    servingSuggestion: 'Squeeze half lemon in warm water, drink morning',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,lemon-water',
    tags: ['hydration', 'vitamin-c', 'morning', 'refreshing'],
  },

  // ===== SWEETENERS =====
  {
    name: 'Honey',
    category: 'sweetener',
    benefits: ['Natural antibacterial properties', 'Contains antioxidants', 'Soothes sore throat', 'Provides quick energy', 'Natural cough suppressant'],
    goodFor: ['energy', 'immunity', 'natural sweetener'],
    nutrients: [{ name: 'Calories', amount: '304 per 100g' }, { name: 'Sugars', amount: '82g' }],
    risks: ['High in sugar, use in moderation', 'Not suitable for infants under 1 year'],
    servingSuggestion: 'Drizzle on oatmeal or use in tea',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,honey',
    tags: ['natural-sweetener', 'antibacterial', 'energy'],
  },
  {
    name: 'Maple Syrup',
    category: 'sweetener',
    benefits: ['Natural sweetener from tree sap', 'Contains antioxidants', 'Contains minerals like zinc and manganese', 'Lower glycemic index than sugar', 'Rich flavor with less needed'],
    goodFor: ['natural sweetener', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '260 per 100g' }, { name: 'Manganese', amount: '165% DV' }, { name: 'Zinc', amount: '11% DV' }],
    risks: ['High in sugar, use in moderation'],
    servingSuggestion: 'Drizzle on pancakes, oatmeal, or in baking',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,maple-syrup',
    tags: ['natural-sweetener', 'minerals', 'pancake'],
  },

  // ===== INGREDIENTS =====
  {
    name: 'Cocoa Powder',
    category: 'ingredient',
    benefits: ['Rich in antioxidants (flavonoids)', 'May support heart health', 'Contains magnesium for muscle function', 'Can improve mood', 'Contains iron'],
    goodFor: ['heart health', 'mood', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '228 per 100g' }, { name: 'Iron', amount: '40% DV' }, { name: 'Magnesium', amount: '100% DV' }, { name: 'Fiber', amount: '33g' }],
    servingSuggestion: 'Add to smoothies, oatmeal, or baking',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,cocoa-powder',
    tags: ['antioxidants', 'mood', 'magnesium', 'flavonoids'],
  },
  {
    name: 'Olive Oil',
    category: 'ingredient',
    benefits: ['Heart-healthy monounsaturated fats', 'Rich in antioxidants', 'Anti-inflammatory properties', 'Supports brain health', 'Staple of Mediterranean diet'],
    goodFor: ['heart health', 'brain health', 'anti-inflammatory', 'cooking'],
    nutrients: [{ name: 'Calories', amount: '884 per 100g' }, { name: 'Healthy Fats', amount: '100g' }, { name: 'Vitamin E', amount: '72% DV' }, { name: 'Vitamin K', amount: '43% DV' }],
    servingSuggestion: 'Use for salad dressing and low-heat cooking',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,olive-oil',
    tags: ['healthy-fats', 'mediterranean', 'cooking', 'antioxidants'],
  },
  {
    name: 'Coconut Oil',
    category: 'ingredient',
    benefits: ['Contains MCTs for energy', 'High heat cooking stable', 'Antimicrobial properties', 'Supports skin health when applied', 'Quick energy source'],
    goodFor: ['energy', 'cooking', 'skin health', 'keto'],
    nutrients: [{ name: 'Calories', amount: '862 per 100g' }, { name: 'Saturated Fat', amount: '87g' }, { name: 'MCTs', amount: 'High' }],
    servingSuggestion: 'Use for high-heat cooking and baking',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,coconut-oil',
    tags: ['mct', 'cooking-oil', 'keto', 'energy'],
  },
  {
    name: 'Apple Cider Vinegar',
    category: 'ingredient',
    benefits: ['May help blood sugar control', 'Supports digestion', 'Contains acetic acid', 'May aid weight loss', 'Natural preservative'],
    goodFor: ['blood sugar', 'digestion', 'weight loss'],
    nutrients: [{ name: 'Calories', amount: '3 per tbsp' }, { name: 'Acetic Acid', amount: '5-6%' }],
    risks: ['Can erode tooth enamel if undiluted', 'May interact with certain medications'],
    servingSuggestion: 'Dilute 1 tbsp in water before meals',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,apple-cider-vinegar',
    tags: ['blood-sugar', 'digestive', 'acetic-acid', 'tonic'],
  },

  // ===== FISH =====
  {
    name: 'Mackerel',
    category: 'protein',
    benefits: ['Very high in omega-3 fatty acids', 'Excellent vitamin D source', 'High in selenium', 'Contains B12 for energy', 'Affordable fatty fish'],
    goodFor: ['heart health', 'brain health', 'bone health', 'mood'],
    nutrients: [{ name: 'Calories', amount: '205 per 100g' }, { name: 'Omega-3', amount: '4.2g' }, { name: 'Vitamin D', amount: '160% DV' }, { name: 'Selenium', amount: '81% DV' }],
    servingSuggestion: 'Grill, smoke, or pan-sear with herbs',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,mackerel',
    tags: ['omega-3', 'vitamin-d', 'seafood', 'affordable'],
  },
  {
    name: 'Sardines',
    category: 'protein',
    benefits: ['Nutrient-dense small fish', 'Excellent calcium source (bones)', 'High in omega-3 and vitamin D', 'Low mercury content', 'Affordable and sustainable'],
    goodFor: ['bone health', 'heart health', 'brain health', 'protein'],
    nutrients: [{ name: 'Calories', amount: '208 per 100g' }, { name: 'Calcium', amount: '38% DV' }, { name: 'Omega-3', amount: '2.2g' }, { name: 'Vitamin D', amount: '68% DV' }],
    servingSuggestion: 'Eat on toast, in salads, or straight from tin',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,sardines',
    tags: ['omega-3', 'calcium', 'sustainable', 'nutrient-dense'],
  },

  // ===== HERBS =====
  {
    name: 'Ginger',
    category: 'herb',
    benefits: ['Powerful anti-inflammatory properties', 'Eases nausea and digestion', 'Contains gingerol antioxidants', 'May reduce muscle soreness', 'Supports immune function'],
    goodFor: ['digestion', 'immunity', 'anti-inflammatory', 'nausea'],
    nutrients: [{ name: 'Calories', amount: '80 per 100g' }, { name: 'Vitamin C', amount: '5% DV' }, { name: 'Magnesium', amount: '12% DV' }, { name: 'Potassium', amount: '5% DV' }],
    servingSuggestion: 'Grate into tea, stir-fries, or smoothies',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,ginger',
    tags: ['anti-inflammatory', 'digestion', 'warming', 'spice'],
  },
  {
    name: 'Turmeric',
    category: 'herb',
    benefits: ['Contains curcumin, powerful anti-inflammatory', 'Potent antioxidant', 'Supports brain health', 'May ease arthritis pain', 'Supports immune function'],
    goodFor: ['anti-inflammatory', 'brain health', 'immunity', 'joint health'],
    nutrients: [{ name: 'Calories', amount: '354 per 100g' }, { name: 'Curcumin', amount: 'High' }, { name: 'Iron', amount: '41% DV' }, { name: 'Manganese', amount: '83% DV' }],
    servingSuggestion: 'Add to curries, golden milk, or smoothies with black pepper',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,turmeric',
    tags: ['curcumin', 'anti-inflammatory', 'golden', 'spice'],
  },
  {
    name: 'Cinnamon',
    category: 'herb',
    benefits: ['May help lower blood sugar', 'Anti-inflammatory properties', 'Contains antioxidants', 'Supports heart health', 'Natural sweet flavor'],
    goodFor: ['blood sugar', 'heart health', 'flavor', 'antioxidants'],
    nutrients: [{ name: 'Calories', amount: '247 per 100g' }, { name: 'Fiber', amount: '53g' }, { name: 'Calcium', amount: '100% DV' }, { name: 'Antioxidants', amount: 'High' }],
    servingSuggestion: 'Sprinkle on oatmeal, coffee, or baked goods',
    imageUrl: 'https://source.unsplash.com/featured/600x400/?food,cinnamon',
    tags: ['blood-sugar', 'spice', 'warming', 'antioxidants'],
  },
];
