export const healthGoalsSeedData = [
  {
    name: 'Lose Weight',
    description: 'Reduce body weight through calorie management, exercise, and healthy eating habits.',
    type: 'weight_loss',
    recommendations: [
      'Eat in a calorie deficit of 300-500 calories below maintenance',
      'Eat protein with every meal to stay full',
      'Drink water before meals to reduce appetite',
      'Walk 30 minutes daily',
      'Limit processed foods and added sugars',
      'Get 7-8 hours of sleep to regulate hunger hormones',
      'Track your food intake for accountability',
    ],
    exercises: ['walking', 'jumping jacks', 'mountain climbers', 'burpees', 'jump rope'],
    foods: ['oats', 'eggs', 'chicken breast', 'broccoli', 'spinach', 'greek yogurt', 'blueberries'],
  },
  {
    name: 'Build Muscle',
    description: 'Increase muscle mass through strength training and adequate protein intake.',
    type: 'muscle_gain',
    recommendations: [
      'Eat in a slight calorie surplus (200-300 calories above maintenance)',
      'Consume 1.6-2.2g of protein per kg of body weight',
      'Focus on compound exercises',
      'Progressive overload: increase weight or reps over time',
      'Get adequate rest between workouts (48 hours per muscle group)',
      'Sleep 7-9 hours for muscle recovery',
      'Stay consistent with training schedule',
    ],
    exercises: ['push-ups', 'squats', 'lunges', 'planks'],
    foods: ['eggs', 'chicken breast', 'salmon', 'greek yogurt', 'quinoa', 'almonds'],
  },
  {
    name: 'Improve Sleep',
    description: 'Enhance sleep quality and duration for better physical and mental recovery.',
    type: 'improve_sleep',
    recommendations: [
      'Go to bed and wake up at the same time daily',
      'Avoid screens 1 hour before bed',
      'Keep bedroom cool and dark',
      'Avoid caffeine after 2 PM',
      'Avoid heavy meals 3 hours before bed',
      'Practice relaxation techniques before sleep',
      'Exercise regularly, but not right before bed',
    ],
    exercises: ['stretching', 'walking'],
    foods: ['banana', 'almonds', 'greek yogurt'],
  },
  {
    name: 'Reduce Sugar Intake',
    description: 'Lower added sugar consumption for better energy, weight management, and overall health.',
    type: 'reduce_sugar',
    recommendations: [
      'Read food labels for hidden sugars',
      'Replace sugary drinks with water or herbal tea',
      'Use fruit to satisfy sweet cravings',
      'Reduce sugar in recipes gradually',
      'Avoid processed snacks and desserts',
      'Eat more protein and fiber to stabilize blood sugar',
      'Plan meals to avoid impulse sugar purchases',
    ],
    exercises: ['walking', 'jumping jacks'],
    foods: ['blueberries', 'banana', 'greek yogurt', 'almonds', 'oats'],
  },
  {
    name: 'Improve Stamina',
    description: 'Build cardiovascular endurance and energy levels through consistent training.',
    type: 'improve_stamina',
    recommendations: [
      'Start with 20 minutes of cardio 3 times per week',
      'Gradually increase duration and intensity',
      'Mix steady-state cardio with interval training',
      'Stay hydrated before, during, and after exercise',
      'Eat complex carbs for sustained energy',
      'Get adequate rest between training sessions',
      'Track progress to stay motivated',
    ],
    exercises: ['walking', 'running', 'jump rope', 'jumping jacks', 'mountain climbers'],
    foods: ['oats', 'banana', 'sweet potato', 'quinoa', 'water'],
  },
  {
    name: 'Mental Wellness',
    description: 'Improve mental health through stress management, exercise, and healthy habits.',
    type: 'mental_wellness',
    recommendations: [
      'Practice 10 minutes of mindfulness or meditation daily',
      'Exercise for at least 20 minutes daily',
      'Limit social media and news consumption',
      'Keep a gratitude journal',
      'Connect with friends and family regularly',
      'Spend time outdoors in nature',
      'Get adequate sleep for emotional regulation',
    ],
    exercises: ['walking', 'stretching', 'planks'],
    foods: ['salmon', 'blueberries', 'spinach', 'avocado', 'water'],
  },
];
