export const healthTipsSeedData = [
  {
    title: 'Drink Water First Thing in Morning',
    category: 'hydration',
    content: 'Drinking a glass of water right after waking up helps rehydrate your body, jumpstarts your metabolism, and improves mental clarity for the day ahead.',
    tags: ['hydration', 'morning-routine', 'metabolism'],
  },
  {
    title: 'Walk After Meals',
    category: 'digestion',
    content: 'A short 10-15 minute walk after meals helps regulate blood sugar levels, improves digestion, and burns extra calories without strenuous effort.',
    tags: ['walking', 'digestion', 'blood-sugar', 'post-meal'],
  },
  {
    title: 'Eat Protein at Every Meal',
    category: 'nutrition',
    content: 'Protein helps maintain muscle mass, keeps you full longer, and stabilizes blood sugar. Aim for at least 20-30g of protein per meal from whole food sources.',
    tags: ['protein', 'nutrition', 'satiety', 'muscle'],
  },
  {
    title: 'Get 7-8 Hours of Sleep',
    category: 'sleep',
    content: 'Quality sleep is essential for physical recovery, mental health, and hormone regulation. Poor sleep increases cortisol and cravings for unhealthy foods.',
    tags: ['sleep', 'recovery', 'hormones', 'health'],
  },
  {
    title: 'Practice Deep Breathing for Stress',
    category: 'mental_health',
    content: 'Deep breathing exercises activate the parasympathetic nervous system, reducing stress and anxiety. Try 4-7-8 breathing: inhale 4 sec, hold 7 sec, exhale 8 sec.',
    tags: ['stress', 'breathing', 'mental-health', 'relaxation'],
  },
  {
    title: 'Eat a Rainbow of Vegetables',
    category: 'nutrition',
    content: 'Different colored vegetables provide different vitamins, minerals, and antioxidants. Eating a variety ensures you get a broad spectrum of nutrients.',
    tags: ['vegetables', 'nutrition', 'antioxidants', 'variety'],
  },
  {
    title: 'Limit Processed Foods',
    category: 'nutrition',
    content: 'Processed foods are typically high in added sugars, unhealthy fats, and sodium while being low in nutrients. Focus on whole, single-ingredient foods as much as possible.',
    tags: ['nutrition', 'whole-foods', 'processed-food', 'health'],
  },
  {
    title: 'Stretch Daily for Flexibility',
    category: 'fitness',
    content: 'Daily stretching improves flexibility, reduces muscle tension, prevents injury, and improves posture. Even 10 minutes a day makes a significant difference over time.',
    tags: ['stretching', 'flexibility', 'mobility', 'injury-prevention'],
  },
  {
    title: 'Track Your Water Intake',
    category: 'hydration',
    content: 'Most people are chronically dehydrated. Aim for 8-10 cups (2-2.5 liters) of water daily. Set reminders if needed, and drink more when exercising or in hot weather.',
    tags: ['hydration', 'water', 'tracking', 'habit'],
  },
  {
    title: 'Eat Mindfully Without Screens',
    category: 'nutrition',
    content: 'Eating while watching TV or scrolling on your phone leads to overeating. Practice mindful eating by sitting at a table and paying attention to your food and hunger cues.',
    tags: ['mindful-eating', 'nutrition', 'habits', 'portion-control'],
  },
  {
    title: 'Start Small with Exercise',
    category: 'fitness',
    content: 'If you are new to exercise, start with 10-15 minutes daily rather than trying to do an hour. Consistency matters more than intensity when building a habit.',
    tags: ['exercise', 'beginner', 'consistency', 'habits'],
  },
  {
    title: 'Reduce Added Sugar Gradually',
    category: 'nutrition',
    content: 'Cutting sugar cold turkey is hard. Reduce gradually: if you take 2 spoons in tea, go to 1, then half. Your taste buds adapt within 2-3 weeks.',
    tags: ['sugar', 'nutrition', 'habits', 'gradual-change'],
  },
  {
    title: 'Include Healthy Fats in Diet',
    category: 'nutrition',
    content: 'Healthy fats from avocados, nuts, seeds, olive oil, and fatty fish are essential for hormone production, brain function, and nutrient absorption.',
    tags: ['healthy-fats', 'nutrition', 'brain', 'hormones'],
  },
  {
    title: 'Take Screen Breaks Every Hour',
    category: 'mental_health',
    content: 'Staring at screens for long periods strains eyes and reduces focus. Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.',
    tags: ['screen-time', 'eyes', 'focus', 'mental-health'],
  },
  {
    title: 'Strength Training is for Everyone',
    category: 'fitness',
    content: 'Strength training builds muscle, increases metabolism, strengthens bones, and improves posture. Aim for 2-3 sessions per week, even with bodyweight exercises.',
    tags: ['strength-training', 'fitness', 'muscle', 'metabolism'],
  },
  {
    title: 'Eat Fermented Foods for Gut Health',
    category: 'nutrition',
    content: 'Yogurt, kefir, sauerkraut, kimchi, and kombucha contain probiotics that support a healthy gut microbiome. Good gut health improves immunity, mood, and digestion.',
    tags: ['probiotics', 'gut-health', 'fermented', 'digestion'],
  },
  {
    title: "Don't Skip Breakfast",
    category: 'nutrition',
    content: 'A balanced breakfast with protein, fiber, and healthy fats stabilizes blood sugar and prevents overeating later. Oatmeal with eggs or Greek yogurt with fruit are great options.',
    tags: ['breakfast', 'nutrition', 'blood-sugar', 'energy'],
  },
  {
    title: 'Use Smaller Plates for Portion Control',
    category: 'nutrition',
    content: 'Using smaller plates creates the illusion of a fuller plate, helping you eat less without feeling deprived. This simple trick can reduce calorie intake by 20%.',
    tags: ['portion-control', 'weight-loss', 'habits', 'psychology'],
  },
  {
    title: 'Take the Stairs When Possible',
    category: 'fitness',
    content: 'Taking stairs instead of elevators adds incidental exercise to your day. Just 5 minutes of stair climbing burns approximately 50 calories and improves cardiovascular fitness.',
    tags: ['cardio', 'daily-habit', 'calorie-burn', 'simple'],
  },
  {
    title: 'Meal Prep on Sundays',
    category: 'nutrition',
    content: 'Spending 1-2 hours on Sunday prepping ingredients or full meals for the week makes healthy eating easier. You are more likely to make good choices when food is ready.',
    tags: ['meal-prep', 'planning', 'habits', 'nutrition'],
  },
  {
    title: 'Cool Down After Every Workout',
    category: 'fitness',
    content: 'A proper cool-down with light stretching helps reduce muscle soreness, prevents injury, and lowers heart rate gradually. Spend 5-10 minutes cooling down after exercise.',
    tags: ['cool-down', 'recovery', 'injury-prevention', 'stretching'],
  },
  {
    title: "Don't Fear Healthy Carbs",
    category: 'nutrition',
    content: 'Complex carbohydrates from whole grains, vegetables, and legumes provide essential energy and fiber. Avoid refined carbs, not all carbs. Your brain and muscles need them.',
    tags: ['carbs', 'nutrition', 'energy', 'whole-grains'],
  },
  {
    title: 'Create a Consistent Sleep Schedule',
    category: 'sleep',
    content: 'Going to bed and waking up at the same time every day, even weekends, regulates your circadian rhythm. This leads to falling asleep faster and waking up refreshed.',
    tags: ['sleep', 'routine', 'circadian-rhythm', 'consistency'],
  },
  {
    title: 'Eat Omega-3s Twice a Week',
    category: 'nutrition',
    content: 'Fatty fish like salmon, mackerel, and sardines should be eaten at least twice weekly for their omega-3 content. Plant sources include walnuts, chia seeds, and flax seeds.',
    tags: ['omega-3', 'nutrition', 'brain-health', 'heart-health'],
  },
  {
    title: 'Keep a Food Journal',
    category: 'nutrition',
    content: 'Writing down what you eat increases awareness of your eating patterns. People who keep food journals consistently lose more weight and make better food choices.',
    tags: ['tracking', 'weight-loss', 'awareness', 'habits'],
  },
  {
    title: 'Exercise in the Morning for Consistency',
    category: 'fitness',
    content: 'Morning exercisers are more consistent because life gets in the way less. Morning workouts also boost metabolism and mental productivity for the rest of the day.',
    tags: ['morning', 'routine', 'consistency', 'productivity'],
  },
  {
    title: 'Seasonal Eating Benefits',
    category: 'nutrition',
    content: 'Eating fruits and vegetables in season provides peak nutrient content and better flavor. Seasonal produce is also more affordable and has a lower environmental impact.',
    tags: ['seasonal', 'nutrition', 'sustainability', 'budget'],
  },
  {
    title: 'Listen to Your Hunger Cues',
    category: 'nutrition',
    content: 'Eat when you are physically hungry, not emotionally hungry. Stop when you are 80% full. It takes about 20 minutes for your brain to register fullness.',
    tags: ['mindful-eating', 'hunger', 'satiety', 'intuitive-eating'],
  },
  {
    title: 'Vary Your Workout Routine',
    category: 'fitness',
    content: 'Doing the same workout every day leads to plateaus and boredom. Mix cardio, strength, flexibility, and HIIT throughout the week for balanced fitness and continuous progress.',
    tags: ['variety', 'fitness', 'plateau', 'balanced'],
  },
  {
    title: 'Stay Hydrated During Workouts',
    category: 'hydration',
    content: 'Drink water before, during, and after exercise to maintain performance and prevent dehydration. Loss of just 2% of body weight in fluids can impair physical performance.',
    tags: ['hydration', 'exercise', 'performance', 'water'],
  },
  {
    title: 'Gratitude Improves Mental Health',
    category: 'mental_health',
    content: 'Writing down three things you are grateful for daily rewires your brain for positivity. This simple practice reduces stress, improves sleep, and increases overall happiness.',
    tags: ['gratitude', 'mental-health', 'happiness', 'daily-practice'],
  },
  {
    title: 'Replace Sugary Drinks with Water',
    category: 'nutrition',
    content: 'Sugary sodas, juices, and energy drinks are the largest source of added sugar in most diets. Replacing just one sugary drink a day with water saves about 150 calories and reduces sugar intake.',
    tags: ['sugar', 'hydration', 'weight-loss', 'drinks'],
  },
];
