export const recipesSeedData = [
  {
    name: 'Chocolate Banana Oatmeal',
    ingredients: ['oats', 'banana', 'cocoa powder', 'milk', 'honey'],
    instructions: ['Cook oats in milk according to package directions', 'Mash half a banana and stir into oatmeal', 'Add cocoa powder and mix well', 'Top with sliced banana and drizzle honey'],
    benefits: ['High fiber from oats keeps you full', 'Natural energy from banana', 'Antioxidants from cocoa powder', 'Quick and satisfying breakfast'],
    prepTime: '2 minutes', cookTime: '5 minutes',
    tags: ['breakfast', 'high-fiber', 'energy', 'quick'],
  },
  {
    name: 'Banana Cocoa Smoothie',
    ingredients: ['banana', 'cocoa powder', 'milk', 'honey', 'ice'],
    instructions: ['Add all ingredients to blender', 'Blend until smooth and creamy', 'Pour into glass and serve immediately'],
    benefits: ['Rich in antioxidants', 'Quick breakfast on the go', 'Natural sugars for energy', 'Kid-friendly'],
    prepTime: '5 minutes', cookTime: '0 minutes',
    tags: ['smoothie', 'breakfast', 'quick', 'antioxidants'],
  },
  {
    name: 'Vegetable Omelette',
    ingredients: ['eggs', 'tomatoes', 'onions', 'spinach', 'salt', 'pepper', 'oil'],
    instructions: ['Beat eggs in a bowl with salt and pepper', 'Chop tomatoes, onions, and spinach', 'Heat oil in a pan over medium heat', 'Saute vegetables for 2 minutes', 'Pour beaten eggs over vegetables', 'Cook until edges set, then fold', 'Serve hot'],
    benefits: ['High protein from eggs', 'Nutrient-rich vegetables', 'Supports muscle repair', 'Low carb and filling'],
    prepTime: '5 minutes', cookTime: '7 minutes',
    tags: ['breakfast', 'high-protein', 'low-carb', 'vegetables'],
  },
  {
    name: 'Grilled Chicken Salad',
    ingredients: ['chicken breast', 'lettuce', 'tomatoes', 'avocado', 'olive oil', 'lemon juice'],
    instructions: ['Season chicken breast with salt and pepper', 'Grill chicken for 6-7 minutes each side', 'Chop lettuce, tomatoes, and avocado', 'Slice grilled chicken', 'Combine all ingredients in a bowl', 'Drizzle with olive oil and lemon juice'],
    benefits: ['Lean protein for muscle maintenance', 'Healthy fats from avocado and olive oil', 'Vitamins from fresh vegetables', 'Satisfying and nutritious meal'],
    prepTime: '10 minutes', cookTime: '15 minutes',
    tags: ['lunch', 'high-protein', 'healthy-fats', 'salad'],
  },
  {
    name: 'Baked Salmon with Sweet Potato',
    ingredients: ['salmon', 'sweet potato', 'broccoli', 'olive oil', 'garlic', 'lemon'],
    instructions: ['Preheat oven to 400°F (200°C)', 'Cut sweet potato into wedges and toss with olive oil', 'Place salmon on baking sheet with sweet potatoes', 'Add broccoli florets around', 'Season with garlic, lemon, salt, and pepper', 'Bake for 20-25 minutes until salmon flakes'],
    benefits: ['Omega-3 fatty acids for heart and brain', 'Complex carbs for sustained energy', 'Vitamins and fiber from broccoli', 'Balanced meal with protein, carbs, and fats'],
    prepTime: '10 minutes', cookTime: '25 minutes',
    tags: ['dinner', 'omega-3', 'balanced', 'meal-prep'],
  },
  {
    name: 'Greek Yogurt Parfait',
    ingredients: ['greek yogurt', 'blueberries', 'almonds', 'honey'],
    instructions: ['Layer Greek yogurt in a glass or bowl', 'Add a layer of blueberries', 'Sprinkle chopped almonds', 'Drizzle with honey', 'Repeat layers and serve'],
    benefits: ['High protein for muscle repair', 'Probiotics for gut health', 'Antioxidants from blueberries', 'Healthy fats from almonds'],
    prepTime: '5 minutes', cookTime: '0 minutes',
    tags: ['breakfast', 'high-protein', 'probiotics', 'no-cook'],
  },
  {
    name: 'Quinoa Bowl with Vegetables',
    ingredients: ['quinoa', 'spinach', 'avocado', 'tomatoes', 'olive oil', 'lemon juice'],
    instructions: ['Cook quinoa according to package directions', 'Let quinoa cool slightly', 'Chop spinach, avocado, and tomatoes', 'Combine quinoa with vegetables', 'Drizzle with olive oil and lemon juice', 'Season with salt and pepper'],
    benefits: ['Complete plant protein from quinoa', 'Healthy fats from avocado', 'Iron and vitamins from spinach', 'Gluten-free meal option'],
    prepTime: '10 minutes', cookTime: '15 minutes',
    tags: ['lunch', 'plant-protein', 'gluten-free', 'bowl'],
  },
  {
    name: 'Avocado Toast with Eggs',
    ingredients: ['whole wheat bread', 'avocado', 'eggs', 'salt', 'pepper', 'lemon juice'],
    instructions: ['Toast whole wheat bread', 'Mash avocado with lemon juice, salt and pepper', 'Fry or poach eggs to preference', 'Spread avocado mash on toast', 'Top with eggs and season'],
    benefits: ['Healthy fats from avocado', 'Protein from eggs for satiety', 'Fiber from whole grain bread', 'Quick and nutritious breakfast'],
    prepTime: '3 minutes', cookTime: '7 minutes',
    tags: ['breakfast', 'healthy-fats', 'quick', 'trending'],
  },
  {
    name: 'Chickpea and Spinach Curry',
    ingredients: ['chickpeas', 'spinach', 'onions', 'garlic', 'ginger', 'tomatoes', 'turmeric', 'coconut milk'],
    instructions: ['Saute onions, garlic, and ginger in oil', 'Add tomatoes and spices, cook 5 minutes', 'Add chickpeas and coconut milk', 'Simmer for 15 minutes', 'Stir in spinach until wilted', 'Serve with brown rice'],
    benefits: ['Plant protein from chickpeas', 'Iron from spinach', 'Anti-inflammatory turmeric', 'Fiber-rich and filling meal'],
    prepTime: '10 minutes', cookTime: '25 minutes',
    tags: ['dinner', 'vegan', 'plant-protein', 'curry'],
  },
  {
    name: 'Berry Protein Smoothie Bowl',
    ingredients: ['blueberries', 'strawberries', 'banana', 'greek yogurt', 'honey', 'granola', 'chia seeds'],
    instructions: ['Blend berries, banana, yogurt and honey until thick', 'Pour into a bowl', 'Top with granola and chia seeds', 'Add extra berries on top', 'Serve immediately'],
    benefits: ['Antioxidants from berries', 'Protein from Greek yogurt', 'Healthy crunch from granola', 'Omega-3 from chia seeds'],
    prepTime: '8 minutes', cookTime: '0 minutes',
    tags: ['breakfast', 'smoothie-bowl', 'antioxidants', 'post-workout'],
  },
  {
    name: 'Lentil Soup',
    ingredients: ['lentils', 'carrots', 'onions', 'garlic', 'celery', 'tomatoes', 'vegetable broth', 'cumin'],
    instructions: ['Saute onions, garlic, carrots and celery', 'Add cumin and cook 1 minute', 'Add lentils, tomatoes and broth', 'Bring to boil then simmer 25 minutes', 'Season with salt and pepper', 'Serve hot with lemon wedge'],
    benefits: ['High protein and fiber from lentils', 'Vitamins from vegetables', 'Warming and comforting', 'Budget-friendly meal'],
    prepTime: '10 minutes', cookTime: '30 minutes',
    tags: ['dinner', 'soup', 'plant-protein', 'meal-prep'],
  },
  {
    name: 'Tuna Avocado Wraps',
    ingredients: ['tuna', 'avocado', 'whole wheat tortilla', 'lettuce', 'lemon juice', 'salt', 'pepper'],
    instructions: ['Drain tuna and flake into bowl', 'Mash avocado and mix with tuna', 'Add lemon juice, salt and pepper', 'Lay lettuce on tortilla', 'Spoon tuna mixture onto lettuce', 'Roll up tightly and slice'],
    benefits: ['Lean protein from tuna', 'Healthy fats from avocado', 'Omega-3 fatty acids', 'No cooking required'],
    prepTime: '10 minutes', cookTime: '0 minutes',
    tags: ['lunch', 'no-cook', 'protein', 'wraps'],
  },
  {
    name: 'Overnight Oats',
    ingredients: ['oats', 'milk', 'greek yogurt', 'honey', 'chia seeds', 'blueberries'],
    instructions: ['Combine oats, milk, yogurt, honey and chia seeds in jar', 'Stir well to combine', 'Cover and refrigerate overnight', 'Top with blueberries in morning', 'Enjoy cold or microwave 1 minute'],
    benefits: ['High fiber keeps you full', 'Protein from Greek yogurt', 'No morning prep needed', 'Omega-3 from chia seeds'],
    prepTime: '5 minutes', cookTime: '0 minutes',
    tags: ['breakfast', 'meal-prep', 'no-cook', 'high-fiber'],
  },
  {
    name: 'Stir-Fried Vegetables with Tofu',
    ingredients: ['tofu', 'broccoli', 'bell peppers', 'carrots', 'soy sauce', 'garlic', 'ginger', 'sesame oil'],
    instructions: ['Press and cube tofu', 'Stir-fry tofu until golden, set aside', 'Saute garlic and ginger in sesame oil', 'Add vegetables and stir-fry 5 minutes', 'Add tofu back and soy sauce', 'Cook 2 more minutes and serve'],
    benefits: ['Complete plant protein from tofu', 'Vitamins from colorful vegetables', 'Low in calories', 'Quick weeknight dinner'],
    prepTime: '10 minutes', cookTime: '12 minutes',
    tags: ['dinner', 'vegan', 'stir-fry', 'vegetables'],
  },
  {
    name: 'Turkey and Vegetable Stir-Fry',
    ingredients: ['turkey breast', 'broccoli', 'bell peppers', 'onions', 'garlic', 'soy sauce', 'olive oil'],
    instructions: ['Slice turkey breast into thin strips', 'Heat oil in wok over high heat', 'Stir-fry turkey until cooked, set aside', 'Saute garlic and vegetables', 'Add turkey back with soy sauce', 'Cook 2 minutes and serve with brown rice'],
    benefits: ['Lean protein from turkey', 'Vitamins from vegetables', 'Low fat and high protein', 'Quick and satisfying meal'],
    prepTime: '10 minutes', cookTime: '12 minutes',
    tags: ['dinner', 'high-protein', 'low-fat', 'stir-fry'],
  },
  {
    name: 'Mediterranean Chickpea Salad',
    ingredients: ['chickpeas', 'cucumber', 'tomatoes', 'onions', 'olive oil', 'lemon juice', 'parsley'],
    instructions: ['Rinse and drain chickpeas', 'Dice cucumber, tomatoes and onion', 'Combine all ingredients in bowl', 'Add olive oil and lemon juice', 'Season with salt and pepper', 'Garnish with fresh parsley'],
    benefits: ['Plant protein and fiber', 'Hydrating vegetables', 'Heart-healthy olive oil', 'No cooking needed'],
    prepTime: '12 minutes', cookTime: '0 minutes',
    tags: ['lunch', 'salad', 'plant-protein', 'mediterranean'],
  },
  {
    name: 'Sweet Potato and Black Bean Bowl',
    ingredients: ['sweet potato', 'black beans', 'avocado', 'corn', 'lime', 'cumin', 'olive oil'],
    instructions: ['Dice sweet potato and roast with cumin and oil at 400°F for 25 minutes', 'Rinse black beans and warm', 'Grill or pan-fry corn', 'Assemble bowl with all ingredients', 'Top with sliced avocado', 'Squeeze lime juice over top'],
    benefits: ['Complex carbs for energy', 'Plant protein from black beans', 'Healthy fats from avocado', 'Vitamin A from sweet potato'],
    prepTime: '10 minutes', cookTime: '25 minutes',
    tags: ['dinner', 'vegan', 'bowl', 'high-fiber'],
  },
  {
    name: 'Peanut Butter Banana Smoothie',
    ingredients: ['banana', 'peanut butter', 'milk', 'honey', 'ice'],
    instructions: ['Add all ingredients to blender', 'Blend until smooth and creamy', 'Pour into glass', 'Optional: add protein powder', 'Serve immediately'],
    benefits: ['Protein and healthy fats from peanut butter', 'Potassium from banana', 'Quick energy for workouts', 'Tastes like a milkshake'],
    prepTime: '4 minutes', cookTime: '0 minutes',
    tags: ['smoothie', 'post-workout', 'protein', 'quick'],
  },
  {
    name: 'Caprese Salad',
    ingredients: ['tomatoes', 'fresh mozzarella', 'basil', 'olive oil', 'balsamic vinegar', 'salt'],
    instructions: ['Slice tomatoes and mozzarella evenly', 'Arrange alternating slices on plate', 'Tuck basil leaves between', 'Drizzle with olive oil and balsamic', 'Season with salt', 'Serve at room temperature'],
    benefits: ['Lycopene from tomatoes', 'Calcium from mozzarella', 'Heart-healthy olive oil', 'Simple and elegant'],
    prepTime: '8 minutes', cookTime: '0 minutes',
    tags: ['lunch', 'salad', 'no-cook', 'italian'],
  },
  {
    name: 'Baked Chicken with Roasted Vegetables',
    ingredients: ['chicken breast', 'carrots', 'zucchini', 'bell peppers', 'olive oil', 'garlic', 'rosemary'],
    instructions: ['Preheat oven to 400°F', 'Cut vegetables into chunks', 'Toss vegetables with oil, garlic and rosemary', 'Place chicken on baking sheet with vegetables', 'Season everything with salt and pepper', 'Bake 25-30 minutes until chicken is cooked'],
    benefits: ['Lean protein for muscle building', 'Vitamins from roasted vegetables', 'Simple one-pan meal', 'Perfect for meal prep'],
    prepTime: '10 minutes', cookTime: '30 minutes',
    tags: ['dinner', 'meal-prep', 'high-protein', 'one-pan'],
  },
  {
    name: 'Mango and Spinach Smoothie',
    ingredients: ['mango', 'spinach', 'banana', 'greek yogurt', 'water'],
    instructions: ['Add all ingredients to blender', 'Blend until completely smooth', 'Pour into glass', 'Add water to adjust consistency', 'Serve chilled'],
    benefits: ['Vitamin C from mango', 'Iron from spinach', 'Protein from Greek yogurt', 'Naturally sweet and refreshing'],
    prepTime: '5 minutes', cookTime: '0 minutes',
    tags: ['smoothie', 'breakfast', 'green-smoothie', 'vitamin-c'],
  },
  {
    name: 'Egg and Vegetable Muffins',
    ingredients: ['eggs', 'spinach', 'tomatoes', 'onions', 'bell peppers', 'salt', 'pepper', 'oil'],
    instructions: ['Preheat oven to 375°F', 'Grease muffin tin', 'Chop vegetables finely', 'Beat eggs and mix with vegetables', 'Pour mixture into muffin cups', 'Bake 15-18 minutes until set'],
    benefits: ['High protein portable breakfast', 'Vegetables for nutrients', 'Make ahead for the week', 'Low carb and filling'],
    prepTime: '10 minutes', cookTime: '18 minutes',
    tags: ['breakfast', 'meal-prep', 'high-protein', 'low-carb'],
  },
  {
    name: 'Grilled Fish Tacos',
    ingredients: ['white fish', 'corn tortillas', 'cabbage', 'lime', 'avocado', 'cilantro', 'cumin'],
    instructions: ['Season fish with cumin, salt and pepper', 'Grill fish 4 minutes each side', 'Warm corn tortillas', 'Shred cabbage and slice avocado', 'Assemble tacos with fish and toppings', 'Squeeze lime and garnish with cilantro'],
    benefits: ['Lean protein from fish', 'Healthy fats from avocado', 'Low calorie and fresh', 'Quick weeknight dinner'],
    prepTime: '10 minutes', cookTime: '10 minutes',
    tags: ['dinner', 'fish', 'tacos', 'fresh'],
  },
  {
    name: 'Walnut and Banana Pancakes',
    ingredients: ['oats', 'banana', 'eggs', 'walnuts', 'cinnamon', 'honey'],
    instructions: ['Blend oats into flour', 'Mash banana and mix with eggs', 'Combine oat flour with banana mixture', 'Fold in chopped walnuts and cinnamon', 'Cook pancakes on greased pan', 'Drizzle with honey'],
    benefits: ['Whole grain oats for fiber', 'Omega-3 from walnuts', 'Natural sweetness from banana', 'Protein-packed pancakes'],
    prepTime: '8 minutes', cookTime: '12 minutes',
    tags: ['breakfast', 'pancakes', 'healthy-twist', 'omega-3'],
  },
  {
    name: 'Chicken and Quinoa Stuffed Peppers',
    ingredients: ['chicken breast', 'quinoa', 'bell peppers', 'onions', 'tomatoes', 'cheese', 'spices'],
    instructions: ['Cook quinoa according to package', 'Cook and shred chicken breast', 'Saute onions', 'Mix quinoa, chicken, onions, tomatoes and spices', 'Cut bell peppers in half and fill', 'Top with cheese and bake 20 minutes at 375°F'],
    benefits: ['Complete protein from chicken and quinoa', 'Vitamin C from bell peppers', 'Balanced meal', 'Great for meal prep'],
    prepTime: '15 minutes', cookTime: '35 minutes',
    tags: ['dinner', 'meal-prep', 'high-protein', 'stuffed'],
  },
  {
    name: 'Cottage Cheese and Fruit Bowl',
    ingredients: ['cottage cheese', 'pineapple', 'strawberries', 'almonds', 'mint'],
    instructions: ['Scoop cottage cheese into bowl', 'Chop pineapple and strawberries', 'Arrange fruits on top', 'Sprinkle sliced almonds', 'Garnish with mint leaves'],
    benefits: ['Slow-digesting casein protein', 'Vitamin C from fruits', 'Healthy fats from almonds', 'Perfect post-dinner snack'],
    prepTime: '5 minutes', cookTime: '0 minutes',
    tags: ['snack', 'high-protein', 'no-cook', 'fruit'],
  },
  {
    name: 'Turkey and Avocado Lettuce Wraps',
    ingredients: ['turkey breast', 'avocado', 'lettuce', 'tomatoes', 'mustard', 'salt'],
    instructions: ['Slice turkey breast', 'Slice avocado and tomatoes', 'Lay lettuce leaves flat', 'Layer turkey, avocado, tomatoes', 'Add mustard and salt', 'Wrap lettuce around filling'],
    benefits: ['Lean protein from turkey', 'Healthy fats from avocado', 'Low carb alternative to bread', 'Quick lunch option'],
    prepTime: '8 minutes', cookTime: '0 minutes',
    tags: ['lunch', 'low-carb', 'no-cook', 'keto'],
  },
  {
    name: 'Roasted Chickpea Snack',
    ingredients: ['chickpeas', 'olive oil', 'cumin', 'paprika', 'salt'],
    instructions: ['Preheat oven to 400°F', 'Rinse and dry chickpeas well', 'Toss with oil and spices', 'Spread on baking sheet', 'Roast 30 minutes until crispy', 'Let cool for extra crunch'],
    benefits: ['High fiber and plant protein', 'Crunchy satisfying snack', 'Healthy alternative to chips', 'Affordable and easy'],
    prepTime: '5 minutes', cookTime: '30 minutes',
    tags: ['snack', 'vegan', 'high-fiber', 'crunchy'],
  },
  {
    name: 'Green Power Smoothie',
    ingredients: ['spinach', 'kale', 'banana', 'apple', 'ginger', 'water'],
    instructions: ['Wash spinach and kale', 'Peel banana and chop apple', 'Add all ingredients to blender', 'Add water and blend until smooth', 'Adjust liquid to preference', 'Serve immediately'],
    benefits: ['Iron from leafy greens', 'Vitamin C from apple', 'Ginger for digestion', 'Nutrient-packed start to day'],
    prepTime: '5 minutes', cookTime: '0 minutes',
    tags: ['smoothie', 'green', 'detox', 'nutrient-dense'],
  },
];
